### ISSUE TITLE
pathlib objects?

### ISSUE THREAD

**Issue by jmccreight** [marshallward/f90nml#102]
Would it be appropriate to request that the writing of pathlib objects be made possible?
Maybe that should be handled upstream and this is wrong tree for barking up?

Thanks!

**Comment by marshallward** [comment]
I haven't used pathlib before, so not sure how or where the integration would be best suited.  Maybe an example would help here?

**Comment by jmccreight** [comment]
Sorry, Pathlib is part of python3 so I thought it wasnt too obscure
https://docs.python.org/3/library/pathlib.html

Here's an argument for using it with a bunch of examples:
https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/

I agree with the basic "it's better most of the time" conclusion. There are still cases where `shutil` and `os` are used to do certain things, which is kinda odd... but still, I think many people are using it.

Seems like it's worth supporting pathlib, if doing this in f90nml is the right place. (I think it is).  Looks like it would just be adding a case to `def _f90repr`.  I would be willing to make a PR if that's correct. 

The example code below show 1) a `str` works, 2) a `pathlib.Path()` object does not work, 3) `str(pathlib.Path())` works. 

🍻 

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pathlib                                                                                

In [2]: import f90nml                                                                                 

In [3]: nml = f90nml.namelist.Namelist({ 
   ...:     'config_nml': { 
   ...:          'file': 'file_string.txt' 
   ...:     } 
   ...: })                                                                                            

In [4]: nml.write('ex.nml')                                                                           

In [5]: nml = f90nml.namelist.Namelist({ 
   ...:     'config_nml': { 
   ...:          'file': pathlib.Path('file_string.txt') 
   ...:     } 
   ...: })                                                                                            

In [6]: nml.write('ex_pathilb.nml')                                                                   
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-2fe46aa9be29> in <module>
----> 1 nml.write('ex_pathilb.nml')

~/anaconda3/lib/python3.7/site-packages/f90nml-1.0.2-py3.7.egg/f90nml/namelist.py in write(self, nml_path, force, sort)
    380         nml_file = nml_path if nml_is_file else open(nml_path, 'w')
    381         try:
--> 382             self._writestream(nml_file, sort)
    383         finally:
    384             if not nml_is_file:

~/anaconda3/lib/python3.7/site-packages/f90nml-1.0.2-py3.7.egg/f90nml/namelist.py in _writestream(self, nml_file, sort)
    412                     self._write_nmlgrp(grp_name, g_vars, nml_file, sort)
    413             else:
--> 414                 self._write_nmlgrp(grp_name, grp_vars, nml_file, sort)
    415 
    416     def _write_nmlgrp(self, grp_name, grp_vars, nml_file, sort=False):

~/anaconda3/lib/python3.7/site-packages/f90nml-1.0.2-py3.7.egg/f90nml/namelist.py in _write_nmlgrp(self, grp_name, grp_vars, nml_file, sort)
    432             v_start = grp_vars.start_index.get(v_name, None)
    433 
--> 434             for v_str in self._var_strings(v_name, v_val, v_start=v_start):
    435                 nml_line = self.indent + '{0}'.format(v_str)
    436                 print(nml_line, file=nml_file)

~/anaconda3/lib/python3.7/site-packages/f90nml-1.0.2-py3.7.egg/f90nml/namelist.py in _var_strings(self, v_name, v_values, v_idx, v_start)
    561 
    562                 if len(val_line) < v_width:
--> 563                     val_line += self._f90repr(v_val) + ', '
    564 
    565                 if len(val_line) >= v_width:

~/anaconda3/lib/python3.7/site-packages/f90nml-1.0.2-py3.7.egg/f90nml/namelist.py in _f90repr(self, value)
    655         else:
    656             raise ValueError('Type {0} of {1} cannot be converted to a Fortran'
--> 657                              ' type.'.format(type(value), value))
    658 
    659     def _f90bool(self, value):

ValueError: Type <class 'pathlib.PosixPath'> of file_string.txt cannot be converted to a Fortran type.

In [7]: nml = f90nml.namelist.Namelist({ 
   ...:     'config_nml': { 
   ...:          'file': str(pathlib.Path('file_string.txt')) 
   ...:     } 
   ...: })                                                                                            

In [8]: nml.write('ex_pathilb2.nml')
```

**Comment by marshallward** [comment]
OK, so you'd like to add support for handling `Paths` as a datatype, in addition to the standard types, is that right?

Currently we only look for explicit types, `int`, `float`, etc, and then fallback to `str` when all those fail.  This seems more of an issue with representing the `Path` for Fortran rather than in Python.  But we could generalise this to use the `__str__` method of a general object.

**Comment by jmccreight** [comment]
That is correct. 
I'm not sure using `__str__` is the right way in general for unidentified types. My thought would be to add 

```
        elif isinstance(value, pathlib.Path):
            return str(value)
```

then, if more cases came up that `return str(value)`, reconsider the approach. Maybe you know of similar, existing use cases that are similar.

**Comment by marshallward** [comment]
I think this may actually be a bug; I had not realised that the `Namelist` constructor was allowing assignment of generic objects:
```
import f90nml
class C(object):
    pass

c = C()
d = {'config_nml': {'x': c}}
nml = f90nml.Namelist(d)    # No error here
print(nml)
# various errors...
```
Basically you are proposing that we should support `Path` as a special case?

I feel like this is probably the point where the user ought to convert their object into a string.  At some point, I don't think the user ought to expect that any object, standard library or otherwise, will have a sensible representation in Fortran.

**Comment by marshallward** [comment]
Also, as a point of reference, `json` would have a similar issue with `Path`:
```
>>> import json
>>> import pathlib
>>> p = pathlib.Path('.')
>>> json.dumps(p)
Traceback (most recent call last):
... 
TypeError: Object of type 'PosixPath' is not JSON serializable
```
Obviously `json` and `nml` don't necessarily need to behave the same, but I think it's not unprecedented to insist that a `Path` be pre-converted to a string.

**Comment by jmccreight** [comment]
I get the argument, as per my initial comment. 

In the json case, json dosent apply `repr`, so why should f90nml apply `str`? I can definitely see the argument that there should be no assumed transformation between the value supplied and the serialization. That's dangerous and a slippery slope.

On the other hand, paths are a major component of f90 namelists. (I'm not sure I've ever seen a complex value in a f90 nml!) For that reason, I think it's desirable to support base python representations of paths and their translation to f90 namelist entries. 

Either way, thanks for considering.

**Comment by marshallward** [comment]
I agree that we shouldn't try to convert `str`, mostly I was just trying to consider how it might be handled, but I think we agree that it would be too uncontrollable.

As for `Path` objects, it's not so much that paths are not important to users. I certainly deal with them a lot in namelists, just as I'm sure they are used often in JSON streams.  It's more that the Fortran runtime does not know what they are and would only see a string.  It would be up to the Fortran program to interpret and use them as a path.

OTOH, the Fortran runtime does recognize a complex number as a unique data format which needs to follow the Fortran syntax, so there needs to be a method to convert them into a readable format that Fortran can understand.

Having said all that, this has revealed a bug (from my perspective at least) which is that we really ought not be storing general objects into the namelists with any expectation that they'll be handled correctly.

There might be some opportunity for supporting more objects and converting to something that Fortran understands, but I don't yet know where that line ought to be drawn.  So for now I'd prefer to keep it to the fundamental types.

Hopefully you can understand my reasoning here, but either way thanks very much for bringing it to my attention.
