### ISSUE TITLE
End commas with nml.write()

### ISSUE THREAD

**Issue by gbromley** [marshallward/f90nml#104]
I am trying to create new namelist files based on a template. Modifying the values is easy enough but the newly written namelist doesn't have end commas. I have tried setting the end_comma flag to True as well as give the write function the "end_comma = True" flag as below. Neither of these options seem to work. 

```
 namelist.write('new_namelist.input', end_comma=True)
```

**Comment by marshallward** [comment]
I think that command was phased out around 1.0, you should set it like this:
```
namelist.end_comma = True
namelist.write('new_namelist.input')
```
If it's still written that way in the docs (and doesn't work) then we should clean that up.

**Comment by gbromley** [comment]
Thanks, no this was my own error.
