### ISSUE TITLE
fails to read arrays of user defined types / structures

### ISSUE THREAD

**Issue by pjoeckel** [marshallward/f90nml#109]
f90nml version: 1.1.2
python: 3.6.9 (default, Oct 29 2019, 10:39:36) [GCC]
OS: SuSe Linux 15.0

f90nml fails to read namelists, which contain entries for initialising arrays of types (fortran structures), such as

<PRE>
  TYPE T_TS_IO
     !
     CHARACTER(LEN=STRLEN_OBJECT) :: name = ''
     CHARACTER(LEN=STRLEN_ULONG)  :: fname = ''
     REAL(DP), DIMENSION(2)       :: vr = (/ -HUGE(0.0_dp), HUGE(0.0_dp) /)
     INTEGER, DIMENSION(2)        :: cnt = (/TS_BD_STOP, TS_BD_STOP/)
     INTEGER                      :: im = TS_IM_PREV
     INTEGER, DIMENSION(6)        :: pdt = (/ -1, -1, -1, -1, -1, -1 /)
     REAL(DP)                     :: offset = 0.0_dp
     !     
  END TYPE T_TS_IO
  TYPE(T_TS_IO), DIMENSION(NMAXTS), PUBLIC :: TS
</PRE>

with the corresponding import.nml

<PRE>
&CTRL_TS
!
TS(1) = 'qbo', '$INPUTDIR_MESSY/qbo/misc/FUB_01_hist_X_QBO_195001_201212.txt',  ,99.90, 0, 0, 0, , , , , , , 0.0,
!
TS(2) = 'solact','$INPUTDIR_MESSY/jval/misc/NRLSSI_FUB1.0_hist_X_solar1AU_19500101_20111231.txt', , , 0, 0, 0, , , , , , , 0.0,
!
TS(4) = 'solspec','$INPUTDIR_MESSY/rad/fubrad/misc/NRLSSI_FUB1.0_hist_X_spec055_19500101_20111231.txt', , , 0, 0, 0, , , , , , , 0.0,
!
/
</PRE>

The output of 

<PRE>
import f90nml
nml = f90nml.read('import.nml')
print(nml)
</PRE>

becomes

<PRE>
 python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value $INPUTDIR_MESSY/qbo/misc/FUB_01_hist_X_QBO_195001_201212.txt is not assigned to any variable and has been removed.
  ''.format(v=next_value)
 python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value 99.9 is not assigned to any variable and has been removed.
  ''.format(v=next_value)
  python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value 0 is not assigned to any variable and has been removed.
  ''.format(v=next_value)
 python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value 0.0 is not assigned to any variable and has been removed.
  ''.format(v=next_value)
 python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value $INPUTDIR_MESSY/jval/misc/NRLSSI_FUB1.0_hist_X_solar1AU_19500101_20111231.txt is not assigned to any variable and has been removed.
  ''.format(v=next_value)
 python3.6/site-packages/f90nml/parser.py:788: UserWarning: f90nml: warning: Value $INPUTDIR_MESSY/rad/fubrad/misc/NRLSSI_FUB1.0_hist_X_spec055_19500101_20111231.txt is not assigned to any variable and has been removed.
  ''.format(v=next_value)
&ctrl_ts
    ts(1:4) = 'qbo', 'solact', , 'solspec'
/
</PRE>

I wonder, if this is a bug or a missing feature?
At least it is a valid namelist ...

**Comment by marshallward** [comment]
Assuming this is the same as #109; closing...
