### ISSUE TITLE
Preserving index for single-element arrays

### ISSUE THREAD

**Issue by marshallward** [marshallward/f90nml#11]
As mentioned in issue #10 , the following namelist

    &test
        a%b(1)%c = 1
    /

is loaded and saved as

    &test
        a%b%c = 1
    /

We ought to see if there is some way to distinguish between these cases (even if Fortran does not). Compatibility also needs to be investigated.

**Comment by jacobwilliams** [comment]
To clarify: this issue is a problem when you are writing your own custom namelists that only change specified elements in an array.  So, in the example above, b is an array in the Fortran code.  If you then create the namelist above to only change the first element, passing it though ````f90nml.read```` and then ````f90nml.write```` then makes the file unreadable (the compiler is now expecting the namelist to include the entire array of b values, since the array index was stripped out).  That is the use case I have in mind.

**Comment by marshallward** [comment]
Are you saying the problem would be in the Fortran program then? In gfortran they seem to be equivalent. For example, if this is my program:

    program dtarray
        implicit none

        type btype
            integer :: c
        end type btype
        type atype
            type(btype), dimension(3) :: b
        end type atype

        type(atype) :: a
        namelist /test/ a

        open(7, file='a.nml')
        read(7, nml=test)

        print *, a%b(1)%c
    end program dtarray

and this is my namelist:

    &test
        a%b%c = 1
    /

then I get the same output, whether or not the index on `b` is included in the namelist.

But I can't say if this is true in other Fortran versions. Or have I got the use case wrong?

**Comment by marshallward** [comment]
It sounds like you are expecting `a%b%c = 1` to vectorise over all elements, is that right?

My understandins is that namelists do not do vectorise. They set the value of the first element (or just the scalar).

**Comment by jacobwilliams** [comment]
Here's a test case (slightly modified from yours):
````Fortran
program dtarray
    implicit none
    
    integer :: istat,i

    type btype
      integer :: c = 0
    end type btype
    type atype
      type(btype), dimension(3) :: b
    end type atype
    type(atype),dimension(3) :: a
    
    namelist /test/ a

    open(7, file='a.nml')
    read(7, nml=test, iostat=istat)
    write(*,*) 'istat', istat
  
    do i=1,3
      write(*,*) a(i)%b%c
    end do
    
end program dtarray
````
So, ```a``` and ```b``` are both vectors.  The namelist:
````fortran
&test
    a%b%c = 1
/
````
produces the following output:
````fortran
 istat        5010
           0           0           0
           0           0           0
           0           0           0
````
It wasn't able to parse the file.  While the namelist: 
````fortran
&test
    a(1)%b(1)%c = 1
/
````
produces the correct result:

````fortran
 istat          -1
           1           0           0
           0           0           0
           0           0           0
````
Even though the istat is -1, it still modified the variable as intended.  I'm using gfortran 5.  I need to verify this with ifort (i think the istat would be 0 for this case on ifort, but I need to verify that).

**Comment by marshallward** [comment]
Ok, I can also confirm this. Gfortran 4.9.2 gives me a runtime error:

    Fortran runtime error: Multiple sub-objects with non-zero rank in namelist object a%b%c

So arrays of arrays of derived types do require explicit indices, and I'll have to track the index a bit better. Thanks for figuring this out.

**Comment by marshallward** [comment]
For the record, this derived type

    type btype
        integer, dimension(3) :: c
    end type btype

with this namelist

    &test
        b%c = 1
    /

also fails. So f90nml should always be tracking the index of a vectored namelist entry, not just for nested dtypes.

**Comment by marshallward** [comment]
Updated change will now preserve the list status of anything with an array. Lists are now only stripped if there is no explicit index (and a single value).

derived type indices are now always printed for lists. `write` still prints out the entire array contents on a single entry though.

**Comment by jacobwilliams** [comment]
Excellent!

I found a case that doesn't work, though.   Say, b has two variables:
```Fortran
&test
    a%b(1)%c = 1
    a%b(1)%d = 2
 /
```

**Comment by marshallward** [comment]
Oops, forgot to remove a `delist`
It should work now.

**Comment by jacobwilliams** [comment]
Terrific! Well, I can't find any more bugs! Excellent work, this is a really nice tool.

**Comment by marshallward** [comment]
(Oops x 2, forgot to commit the change)

Thanks for the feedback! I don't think I would have caught most of this stuff otherwise :)
