### ISSUE TITLE
Type Annotations for Documentation

### ISSUE THREAD

**Issue by pgierz** [marshallward/f90nml#114]
Hello,

before my request -- a huge thank you for building a nice namelist parser! we are using it in some of our own projects and having to re-invent this from scratch would have been a real pain. Great work!!!

Minor thing, but would it be possible to include types for attributes of the `Namelist` class in the documentation? If I need to modify them for a particular purpose, I need to currently make sure by looking at the source code that I'm doing the right thing, including this info in readthedocs would save a little bit of time.

**Comment by marshallward** [comment]
There is something like that here (scroll past `Parser` to get to `Namelist`):

https://f90nml.readthedocs.io/en/latest/usage.html#classes

Is that what you mean?  Or is it something else?

**Comment by pgierz** [comment]
Yes, in that direction. But, for example, can the documentation detect that the `uppercase` attribute should be a Boolean?

**Comment by marshallward** [comment]
Oh, right, I see.  Yes, that would be helpful!   Thanks for the suggestion, I will try to add that info.

**Comment by marshallward** [comment]
Trying to get this finished, but just wanted to add this detail (mostly to myself).

When all of the configurable variables were replaced with properties, this caused Sphinx to replace the type with the generic `property` label in the autodocumentation.

I am looking into some way to override or clarify this in Sphinx, rather than explicitly adding this info to the docstring.

**Comment by marshallward** [comment]
I've included type and default values for each property of `Parser` and `Namelist`.  It might need some further edits, but is this the sort of thing you had in mind?

**Comment by pgierz** [comment]
yeah that looks like exactly what I needed! Perfect!

**Comment by marshallward** [comment]
Great!  Sorry it took so long, I've been trying to prioritize other things these days.

I'll close this one.
