### ISSUE TITLE
Break a super long line namelist entry into multi-line input

### ISSUE THREAD

**Issue by xic** [marshallward/f90nml#119]
Hi guys,

I am new in this group. I want to thank the author and the contributors for making such an excellent tool for my research.

Here is my challenge. My code generates a namelist entry that contains a list of files, e.g., a list of reanalysis data to nudge a GCM run. Unfortunately, the model cannot handle a super-long line of namelist entry:

```bash
file_names = './INPUT/20200610_00Z_T1534.nc , ./INPUT/20200610_06Z_T1534.nc , ./INPUT/20200610_12Z_T1534.nc , ... ./INPUT/20200620_00Z_T1534.nc'
```

One hack to get around this problem is to break this entry into multiple lines:

```bash
file_names = './INPUT/20200610_00Z_T1534.nc ,
./INPUT/20200610_06Z_T1534.nc ,
./INPUT/20200610_12Z_T1534.nc ,
...
./INPUT/20200620_00Z_T1534.nc'
```

Is there a way to implement this hack at the f90nml level? I tried the following approaches, but no luck:

* Add line break in the string:

```python
input_nml['file_names'] = """'file1', \n'file2.nc', \n..."""
```

* Add line break in the array items:

```python
input_nml['file_names'] = ['file1, \n', 'file2, \n', ...]
```

Both are "flattened" in the final results.

* Hacking with shell scripts:

  ```python
  input_nml['file_names'] = """`echo $nudge_files  | sed "s/ /', \n'/g"`"""
  ```

where nudge_files are a list of files separated by spaces, and the resulting namelist sits in a shell script.
This results in a strange behavior that the parsed string replace the single quote into two single quotes:

```bash
file_names = '\`echo $nudge_files  | sed "s/ /'', \n''/g"\`'
```

Therefore, is there a way to break a super long line namelist entry into multi-line input from f90nml? Any help is much appreciated!

Cheers,

Xi

**Comment by marshallward** [comment]
I don't think f90nml can currently do this.  We can split arrays over multiple lines, but not individual strings.  If your string is longer than some internal namelist line length limit for the compiler, then in all likelihood it will not work.  In this case, I'd consider this a f90nml bug that we should fix.

(I don't see a character limit anywhere in the standard, but it would not surprise me if namelists were also constrained by the 132-character limit, as in source code.)

There's no reason why we should not be able to split such lines.  Your first example is a valid namelist record and should give the result that you want.  But I'm not sure how to indicate this it at the Python level.

It would not be too hard to apply a hard-break to the string to ensure that it fits within some line limit (say 80 or 132 characters), but it would not necessarily be pretty or easily parseable.

I currently don't have any good ideas on how to indicate this.  The best idea I have at the moment is to somehow insert tokens which would be conditionally recognized as line breaks.  (Using `\n` is an option but could be problematic for a few reasons, which I'll skip over for now.)

Sorry that I don't have better news at the moment, but perhaps this problem can be fixed without much work.

If you can name the compiler and upload an example namelist with this problem, then I can try out a few ideas.

**Comment by marshallward** [comment]
Starting to think through this issue.  For this namelist:
```
&a_nml
   s = "abc
def"
/
```
the value of `s` is `abcdef` regardless of namelist formatting, and (if `nml` is the namelist) we want `nml['a_nml']['s']` to return  `abcdef`.  So at the access level, we do want to remove this `\n` formatting and do not want to give any impression that it is part of the data.

If we were to preserve it, then one option is to somehow retain the original formatting in metadata, say `nml['a_nml']['_raw']['s'] = "abc\ndef"`  (not the most intuitive choice, but in line with existing examples).

The parser currently does not track this information, but it could be stored during `f90nml.read()`.  (No comment on how easy it would be though...)

Similarly, if one wanted to control the output formatting of a new namelist then one can manipulate the `_raw` record to meet their needs.

----

Finally, as perhaps a much simple solution, we could simply track the length of strings during `nml.write()` and just do our best to break them along obvious tokens like spaces or - as a last resort - apply the line break at the character length limit (currently defaults to 72).

This could be a conditional flag which is disabled on default.

----

The first solution would provide greater control, but the second may be the more practical solution here.

**Comment by xic** [comment]
Thank you for such a quick response. I agree that the standard does not have a character limit. Unfortunately, the is a library layer from my model imposes such a constraint (256 characters).

May I propose two possible solutions?

1. Instead of breaking for arbitrary strings, only break array inputs when necessary.

2. Allow shell script expression parsing. This usually works with the f90nml as is, but I encountered strange behavior when both ' and " are in the same string. Consider the following:

```python
input_nml['some_key'] = """sed "s/ /', \n'/g"`"""
```

It produces

```shell
some_key = 'sed "s/ /'', \n''/g"`'
```

in the resulting output.

I hope it helps.

Cheers,

Xi

**Comment by marshallward** [comment]
Not exactly sure why you have embedded shell commands here, nor have I ever thought about how docstrings (`""" ... """`) ought to be interpreted, but it seems that the docstring delimiter is being interpreted as `'`, possibly because `'` is default, or possibly because the first instance of `"` is forcing Python to default to `'` as the outer delimiter.

Either way, when this is converted to a Fortran string, this is causing the `'` to be read as a character inside the string.  In Fortran, a quote delimiter is escaped by repeating it, so `"""abc'def"""` in Python becomes `'abc''def'` in Fortran.

If that is what's happening here, then the behavior is correct.  I'm not sure this is something that can or ought to be changed.

How are these shell commands being executed?  Is Fortran reading the namelist and then passing the command to a shell?  In that case, you may actually want the repeated quotes.

**Comment by xic** [comment]
Apologies for the confusion. Below is my current "working" driver script demo:

```bash
...
set nudge_files = "file1 file2 file3 ..." # space divided list.
...

cat >! input.nml <<EOF
...
file_names = '`echo $nudge_files  | sed "s/ /', '/g"`' # this line breaks the long entry into multi-lines
...
/
EOF

$RUN_CMD # this line runs the model, which reads the updated input.nml

```

That's the hack. But I stuck at trying to use f90nml to set `input_nml['file_name']` to above value.

Thank you very much for your time and effort!

Cheers,

Xi

**Comment by marshallward** [comment]
OK I see, you run the script through bash which executes the command and splits the list, and the `` ` `` delimiters let you nest the `'` without introducing any escape characters.

I don't know if there's some way to output something like this without ignoring the string escape rules, but I understand your problem.

In this case, let's try to find some way to split the string when it exceeds a character limit.

**Comment by xic** [comment]
Exactly, great!

**Comment by marshallward** [comment]
I've created a branch which breaks strings based on `self.column_width` across multiple lines:

https://github.com/marshallward/f90nml/tree/string_split

Can you give this a try?

**Comment by xic** [comment]
Thank you for the quick action. I did several tests, and your update yields promised behavior. Good job, and thank you!

I also attempted to reach some "corner case tests" and found some interesting results. Please try the following code snippet:

```python
import numpy as np
import f90nml

ctrl_nml = """
&ctrl_nml
    file_names = 'null'
/
"""
file_lists = ['file{}'.format(n) for n in np.arange(41)]

nml1 = f90nml.reads(ctrl_nml)
nml2 = f90nml.reads(ctrl_nml)
nml3 = f90nml.reads(ctrl_nml)

nml1['ctrl_nml']['file_names'] = file_lists
print(nml1)

file_names = "', '".join(file_lists)
nml2['ctrl_nml']['file_names'] = file_names
print(nml2)

file_names = '", "'.join(file_lists)
nml3['ctrl_nml']['file_names'] = file_names
print(nml3)
```

The goal of the code is to provide a (long) file list to the model via the namelist. All three approaches got proper line breaks. The first method uses f90nml to assign a list of strings to the namelist and gets correct results. The latter two tries to form a single string containing the entire list (this happens in many "all-in-one" shell scripts.) The long strings are wrapped with unmatched single- or double-quotes. I don't consider the latter two cases are bugs because such properties can be valuable when the user wants to keep the input a single string, e.g., a long file path with special characters. Therefore, I found myself a "best practice" for using f90nml:

If I want my namelist entry to take a list-type input, feed f90nml an actual list.

The updated version fixes all my problems. Thank you!

Cheers,

Xi

**Comment by marshallward** [comment]
@xic Based on feedback in #131, I think that I will make this string split behavior optional and will control it with a flag.  Something like this:
```
nml = f90nml.reads(ctrl_nml)
nml.strict_col_width = 80
print(nml)
```
It would be good to get your feedback and check if this is an option for you.

**Comment by marshallward** [comment]
I'm still thinking how to control this behavior.  I may just use a logical flag (`nml.split_strings`).
