### ISSUE TITLE
Cosmetic Ideas

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#12]
Everything seems to work great now.  So, now all I have are some possible cosmetic suggestions.  These are somewhat minor, so feel free to ignore them.
* Maybe have the ability to specify for the ```write``` method the string to use for the True and False values.  Currently it always uses ```.true.``` and ```.false.```.  Intel (and probably others), also accepts ```T``` and ```F```.  
* Maybe also have the option to specify if we want to force a comma to be written after each variable.  It looks like currently it only does this for strings that contain commas and to separate array elements?  The compiler seems to be OK with that.  However, somebody out there may be parsing namelists and expecting the ending commas (I think I had something like that at one point).
* Maybe allow caller to specify the number of spaces to be used for indenting?

Perhaps these could be optional arguments?  Something like:
````Python
n = f90nml.read('test.nml')
n.write( 'test2.nml', force=True, indent=2, true_str='T', false_str='F', force_commas=True )
````
Again: minor stuff, but maybe nice to have (there could be other options as well).

**Comment by marshallward** [comment]
Thanks, these are great suggestions.

The indentation is easy enough to set, and the trailing commas needs to be sorted out anyway (e.g. #5).

As for the True/False values, I do check for the cases you mention at input. The Fortran standard actually only requires a T or an F, with an optional leading dot, so `.true. = .T = T = Talse = ...` !

In my perfect world, everyone would use `.true.` and `.false.`, but this is easy enough to implement so I can try to get it working.

**Comment by marshallward** [comment]
I just merged a bunch of changes that adds the following properties:

`nml.colwidth`
    Number of columns in file (values extending past 72 stay on the line)

`nml.indent`
    Value indentation, either an integer (number of spaces) or a whitespace string (e.g. \t)

`nml.end_comma`
    Logical, print end commas after values
    (currently appends a comma to the last value, need to fix)

`nml.uppercase`
    Logical, Display group and variable names as uppercase

`nml.floatformat`
    Explicit floating point format (as in python's `string.format`)

`nml.truerepr`
`nml.falserepr`
    Set the string representation of `True` and `False`

There are some checks to make sure that values are appropriate, but I may have missed some stuff.

**Comment by jacobwilliams** [comment]
I was just about to make a ticket suggesting you add a way to change the floating point format. Then I saw you had already added it. Thanks!!

**Comment by marshallward** [comment]
Good to hear :)
I'm only keeping the issue open to motivate myself to document all the formatting changes.

**Comment by marshallward** [comment]
This is now documented, so I'm closing the ticket.
