### ISSUE TITLE
Compression of output arrays

### ISSUE THREAD

**Issue by HoWol76** [marshallward/f90nml#122]
Fortran also allows namelists to be of the form

    &nml
    arr(1:10) = 2*1, 4*2, 5, 3, 2*5
    /

At the moment, `f90nml` seems to be able to read such a namelist, but not write it in this form. I have an issue where I have large arrays (several thousand values) where almost all values are identical. Being able to compress this data would make my namelists far more readable.

**Comment by marshallward** [comment]
I agree, this would be good to implement, perhaps with a control flag.   This also falls under #24 to some extent since there ought to be more ability to shape output.

I'm not sure I have the bandwidth to work on this but will take it on board.  

(Also nice to hear from you again, Holger!)

**Comment by HoWol76** [comment]
Could you give me some pointers on where you would insert the code necessary to make this change? I could play around with it a bit and then maybe even implement it.

**Comment by HoWol76** [comment]
I think I found it. Made a pull request.

**Comment by marshallward** [comment]
Addressed in #123
