### ISSUE TITLE
Patch does not add new namelists

### ISSUE THREAD

**Issue by Cory-Kramer** [marshallward/f90nml#130]
If I start with a file `sample.nml` that contains a single namelist
```
&first_nml
    a = 100
    b = .false.
/
```

I can use `patch` to either modify values in this namelist, or add new values to this namelist
```
import f90nml
patch_nml = {'first_nml': {'a': 200, 'c': 1.0}}
f90nml.patch('sample.nml', patch_nml, 'patched.nml')
```
This will correctly produce a new file `patched.nml` with the contents
```
&first_nml
    a = 200
    b = .false.
    c = 1.0
/
```

However if I try to create a new namelist entirely (for example `second_nml`) patch will silently ignore this namelist
```
import f90nml
patch_nml = {'second_nml': {'x': 100, 'y': 200}}
f90nml.patch('sample.nml', patch_nml, 'patched.nml')
```
Now `patched.nml` simply contains the original unmodified contents
```
&first_nml
    a = 100
    b = .false.
/
```
The expected/desired behavior would be to create `patched.nml` that contains
```
&first_nml
    a = 100
    b = .false.
/

&second_nml
    x = 100
    y = 200
/
```

**Comment by marshallward** [comment]
Thanks for finding and reporting this.  We were checking for unused variables inside of groups, but not unused groups.  I have applied a fix to the main branch (1a0c3bcfcf08391be7ff4fa1cf6f32bb5466f75c).

There was also a bug in patching new variables in existing groups where indentation was applied twice.  That has also been fixed.

**Comment by Cory-Kramer** [comment]
Thanks @marshallward really appreciate it!

**Comment by marshallward** [comment]
Great news; I've modified one of the tests to catch this in the future.

I will close this issue.
