### ISSUE TITLE
Order of repeated blocks not preserved when mixed with other named blocks

### ISSUE THREAD

**Issue by jpf-x** [marshallward/f90nml#132]
File file contains 
```
&block00
i=1
k=2
&end
&block01
m=0
n=1
&end
&block00
j=3
z=4
&end
```
The statement f90nml.write(f90nml.read(file),outfile) will result in outfile containing
```
&block00
i=1
k=2
/
&block00
j=3
z=4
/
&block01
m=0
n=1
/
```
where order of namelist blocks has not been preserved.

**Comment by marshallward** [comment]
This is not currently something that is easily resolvable since namelist groups are accessed by name.  When repeated groups are encountered, we try to preserve the original ordering, but do not attempt to track the position of subsequent instances of the same group.

There may be some way to do this within the `OrderedDict` or perhaps we could internally keep them as a list but apply some behind-the-scenes methods to generate the list, but at the moment I don't know how to proceed.

Unfortunately it will take some thought and experimentation to do as you suggest, and I cannot promise anything at the moment.

**Comment by jpf-x** [comment]
Understood. I've looked through your code and - without being well enough acquainted with it yet - I imagine a method complementing Parser.read could be defined that would return a list of tuples [('group_id',Namelist()),...] rather than a dictionary of lists {'group_id':[Namelist(),...]}. Maybe this will spark some idea. Will keep digging to see if I can see any way. Thanks for sharing your tool. It's great!

At the moment, the Fortran program I'm dealing with reads groups in the manner of the dummy example, with processing in between. There is the possibility of any number of block00 groups, with termination of the program initiated by particular input in that group. This is just to explain motivation of issue.

**Comment by marshallward** [comment]
Thanks for explaining the context.  I have created a bit of a paradox by storing the namelist as a `dict` since nearly all Fortran programs access the namelist serially.  Usually it doesn't matter, but your case is one of the few times when it is an issue.

I had an idea to store the subsequent duplicates with underscores and indices, e.g. `block00`, `_block00_01`, `_block00_02`, etc which are internally stored serially but construct a list whenever `nml['block00']` is referenced.  When printing the output, the `_`...`_##` wrapper could be stripped from the name.

Usually `_` is reserved for metadata, but I could see it working if we are careful.

**Comment by jpf-x** [comment]
Just beginning the process to see what might work, I copied the _readstream method to _readstream_tolist method, and just changed 

`nmls = [] # Namelist()`

and replaced
```

                    # Append the grouplist to the namelist
                    if g_name in nmls:
                        g_update = nmls[g_name]

                        # Update to list of groups
                        if not isinstance(g_update, list):
                            g_update = [g_update]

                        g_update.append(g_vars)

                    else:
                        g_update = g_vars

                    nmls[g_name] = g_update
```

with

```
nmls.append((g_name,g_vars))
```

This gives the desired .read result anyway. Now on to the write.
By the way, I am being completely selfish in trying to make this work for my case, so I'm sure I've broken lots of things. Perhaps a keyword option "tolist" or something rather could indicate processing this way and preserve backward compatibility.

**Comment by marshallward** [comment]
The current behavior is to imagine as if a virtual Fortran program has parsed the entire file and read its contents into equivalent variables.  In this case, reading a namelist twice would clobber the existing values.

Your suggestion is a more explicit traversal of the file, and provides a more accurate description of the namelist.

The first approach made more sense to me years back when I first put this together, and before I really understood the serialized nature of namelist I/O.  But I have to admit that your approach makes a lot of sense as well, though perhaps less convenient.

Given that the `OrderedDict` preserves the original ordering, I would guess there is a good way to retain the key-based access while also retaining the original order.

**Comment by jacobwilliams** [comment]
I hope the current behavior doesn't break! 😀 I use multiple namelists with the same name where the order matters too, but mine are always contiguous in the file. When they're read I also depend on them being in a list. And I don't care about the order of the other namelists in the file.

**Comment by jpf-x** [comment]
Ok this might be safer with goal of preserving current behavior. (forget previous attempt)

In **parser.Parser._readstream**, the following modification is made (in proposed change)
Change
```
        nmls = Namelist()
```
to

```
        nmls=Namelist() # (no change, just for reference)
        nmls['order']=[]
```

where the 'order' keyword could change to whatever makes sense and wouldn't conflict with a namelist named 'order'.
Then, right after `g_update` is defined, this
replace

```
nmls[g_name] = g_update
```

with

```
                    if isinstance(g_update,list):
                      nmls['order'].append((g_name,len(g_update)-1))
                      nmls[g_name] = g_update
                    else:
                      nmls['order'].append((g_name,0))
                      nmls[g_name] = [g_update]
```

Then in **namelist.Namelist._writestream** the following would impose the order. (commented out replaced)

```
        for grp_name,ix in sel['order']: #grp_name, grp_vars in sel.items():
            grp_vars=sel[grp_name][ix]
            # Check for repeated namelist records (saved as lists)
            if isinstance(grp_vars, list):
                for g_vars in grp_vars:
                    self._write_nmlgrp(grp_name, g_vars, nml_file, sort)
            else:
                self._write_nmlgrp(grp_name, grp_vars, nml_file, sort)
```

It's not polished, but the concept works. (tried it and it works for my test cases)
In this last change, `grp_vars` is never a list, of course.

**Comment by marshallward** [comment]
I would guess that the order does not need to be explicitly tracked.  This is already being implicitly tracked in the `OrderedDict`.  (`Namelist` is a subclass of `OrderedDict`).   Groups are stored in the order which they are added.  When groups are not repeated, we are already preserving the order.

I think all we need to do in this case is just provide a different internal name.  After that, `__getitem__` can be modified to return a list of all groups if multiple groups share the same (public) name.

**Comment by jpf-x** [comment]
I agree that solution is also valid.
But, it doesn't really utilize the distinguishing characteristic of the `OrderedDict`, per se. That is that key entries are retrieved in same order as entered when the `OrderedDict` is used as an iterator, for example. But since here we're not updating the dictionary but rather updating a value referenced in the dictionary (a list of `Namelist`s), that behavior doesn't provide any relief.
Very possible I'm missing something... still studying your code.

**Comment by jacobwilliams** [comment]
Also probably __setitem__?

**Comment by jpf-x** [comment]
Perhaps using a parenthesis for internal naming would work. They're certainly not allowed in namelist name.
A namelist group `BLOCK00` might be internally referenced as `BLOCK00(0`, `BLOCK00(1`, etc. as new blocks are encountered.

Then when time comes to write in **namelist.Namelist._write_nmlgrp**, could replace

`print('&{0}'.format(grp_name), file=nml_file)`

with

`print('&{0}'.format(grp_name.split('(')[0]), file=nml_file)`

For reading, as you mentioned, you could override `__setitem__` as 

```
def __setitem__(self,key,val):
  last_key=[x for x in self.__dict__.keys() if k==x.split('(')[0]]
  if last_key:
    n=int(last_key[-1].split('(')[1])
  else:
    n=0
  self.__dict__[k+f'({n}']=val
```

**Comment by marshallward** [comment]
I would keep the naming scheme simple, noting a couple things:

* Fortran does not permit variables to begin with underscores (`_`) which up a namespace for internal data like this.  Similar methods are used to track metadata such as start index when converting to/from JSON and YAML.

* I would avoid tokens which could have semantic meaning, such as parentheses.

I was imagining something like this: `_dup_[name]_[#]`, e.g. `_dup_block00_1`.  Some thoughts:

* The leading `_` would indicate a nontrivial parsing of the variable name

* `_dup` would indicate that it was a repeated value, and the `_dup_` + `_[#]` could be stripped from the name, also catching [#] as the element ID in the list.

* This should not create any conflicts with any `_` in the group name, nor with a variable ending in its own suffix; `block_1` -> `_dup_block_1_1` is parseable)

* The `_dup_[name]_0` could be aliased to the original value.

There are other smaller issues to address, but I could see this supporting repeated groups and capturing the original content of the namelist, while also not changing existing behavior.  `nml['block00']` would generate and return the list of repeated groups, and writing a group would still overwrite the existing value.

(I'm not sure that I like the `_dup` prefix name, but in the end it probably does not matter.  If handled correctly, users should never even see it.)

**Comment by jpf-x** [comment]
That's a lot of work, but it might make other features easier to implement also. For example, one related desired feature is the ability to `insert` a new namelist in a particular location (among other namelists; related because it has to do with observing order).
To that end, it appears you can currently add a new namelist (patch) but without specifying location. May call for a new class (say, `Book`), which would act more like a `list`. Then you'd just have a `Book` of `Namelist`s rather than a `Namelist` of `Namelist`s. The namelist is not inherently nested anyway.

In the proposed changes I've attempted to impact/touch existing code as little as possible. Not sure if that's important to you, but that's why I favored the direct approach of governing order explicitly.

**Comment by marshallward** [comment]
I've created a branch with something close to the proposed implementation:

https://github.com/marshallward/f90nml/tree/grp_repeat
```
>>> import f90nml
>>> nml = f90nml.read('test.nml')
>>> nml
Namelist([('block00', Namelist([('i', 1), ('k', 2)])), ('block01', Namelist([('m', 0), ('n', 1)])), ('_grp_block00_1', Namelist([('j', 3), ('z', 4)]))])
>>> print(nml)
&block00
    i = 1
    k = 2
/

&block01
    m = 0
    n = 1
/

&block00
    j = 3
    z = 4
/
>>> nml['block00']
[Namelist([('i', 1), ('k', 2)]), Namelist([('j', 3), ('z', 4)])]
>>> nml['block00'][0]
Namelist([('i', 1), ('k', 2)])
```
Surely much more work to do, but this captures what I was trying to propose.

**Comment by marshallward** [comment]
Additional notes:

* I am considering re-naming the original record, e.g. remove `block00` and re-add the original entry as `_grp_block00_0`.  This would remove the potentially inconsistent interpretation of `nml['block00']`, which appears as a record in the `repr()` but returns a list of groups.
* On the same note, the whole `self._cogroups` array is probably redundant, and it may even be better to just dynamically generate the list in `__getitem__` whenever `nml['block00']` is called.  There may be performance issues here, but I doubt they are significant.
* Equality testing still needs to be considered.  This is why `test_grp_repeat` is failing, and I am not yet even sure how to define equality.
* The `add_cogroup` function is sufficient to append a new group to an existing group, but it would be helpful to consider other functionality.
 
There may be limits to what we can do here.  But ideally I would like for these questions to be answered in `Namelist`.  The `Parser` should use the API as defined in `Namelist`.

**Comment by marshallward** [comment]
I have completed some more work on this, and can now modify the elements.

This required introduction of a `Cogroup` object where manipulation of its list elements also updates the equivalent value in the `Namelist`.
```python
>>> import f90nml 
>>> nml = f90nml.read('test.nml')
>>> nml['block00']
[Namelist([('i', 1), ('k', 2)]), Namelist([('j', 3), ('z', 4)])]
>>> nml['block00'][0]
Namelist([('i', 1), ('k', 2)])
>>> nml['block00'][1]
Namelist([('j', 3), ('z', 4)])
>>> g = f90nml.Namelist({'x': 0})
>>> nml['block00'][1] = g
>>> nml['block00']
[Namelist([('i', 1), ('k', 2)]), Namelist([('x', 0)])]
>>> nml['block00'][1]
Namelist([('x', 0)])
>>> print(nml)
&block00
    i = 1
    k = 2
/

&block01
    m = 0
    n = 1
/

&block00
    x = 0
/
```
There is still some remaining things to consider, such as equality testing or deleting elements, but I am overall happy with how this is working.

**Comment by marshallward** [comment]
I have updated the branch to support `del`, and I would like to finalize this work, but there is some question about how to define equality.

In the current version, this namelist
```fortran
&repeat_nml
    x = 1
/
&repeat_nml
    x = 2
/
```
will produce a `Namelist` which reports equivalence to this `dict`:
```python
nml = {
    'repeat_nml': [{'x': 1}, {'x': 2}]
}
```
In the new version, it will report equivalence to a different dict:
```python
nml = {
    'repeat_nml': {'x': 1},
    '_grp_repeat_nml_1': {'x': 2}
}
```
and the original equivalence will report false.

A related issue is the change to the `repr()` of the `Namelist`, which will expose these internal keys to the user:
```python
>>> nml = f90nml.reads('&repeat_nml x = 1 / &repeat_nml x = 2/')
>>> nml
Namelist([('repeat_nml', Namelist([('x', 1)])), ('_grp_repeat_nml_1', Namelist([('x', 2)]))])
```
I would prefer that data be accessed as `nml['repeat_nml'][1]` over `nml['_grp_repeat_nml_1']`, but `repr()` needs to be accurate and the current list pattern has ambiguous ordering, so I think this must change.

For the same reason, I believe that the list output is (now) ambiguous and it is correct for the current equality test to fail, and the test should be updated.

I recognize this as a "big decision" and don't want to change it lightly.  Unfortunately I don't have any effective means to solicit feedback, so it might take some time or effort to come to a decision.

**Comment by marshallward** [comment]
I am going to push this change and modify the equality test.  Unfortunately the only realistic way for me to get feedback is to do a release and wait for the bug reports.

I'll monitor the situation and keep this issue open as the situation evolves.

**Comment by marshallward** [comment]
I have pushed a fix for this issue.  I believe it to be working so I will close this issue, but please re-open if any problems are detected.
