### ISSUE TITLE
Feature Request for Metadata: confusion from the documentation

### ISSUE THREAD

**Issue by MuellerSeb** [marshallward/f90nml#135]
Hi there,

first of all thanks for this really helpful package. We wanted to add metadata to the dict representation of a namelist and the [documentation](https://f90nml.readthedocs.io/en/latest/usage.html#f90nml.namelist.Namelist.todict) says:
> Since Fortran variables and names cannot start with the _ character, any keys starting with this token denote metadata, such as starting index.

Problem is, when adding metadata this way to a dict
```python
nml_dict["nml1"]["_metadata"] = 1
```
it will be written to file by f90nml, when writing out the namelist.

I first thought, every name with underscore gets excluded. Actually I would love that feature.

What do you think?

Sebastian

**Comment by marshallward** [comment]
I agree, this sounds like a good suggestion.  Those variables should never appear in the namelist.

It sounds like you are adding your own metadata fields, rather than working with the existing ones (start index, for example).  Is that right?

I think we might need to reserve the right to take over certain metadata variables in the future, but suppressing them for now should be no problem.

**Comment by marshallward** [comment]
I am looking at this now, and I think you are asking for something slightly different than what is being referenced in the documentation.

The metadata in the docs refers to fields in non-other formats like JSON, which do allow underscore names, and document how to store data which cannot be saved in those formats, such as complex types or array index information.  (The reference to valid Fortran names was to demonstrate that there could be no keyname collisions.)

Initially, I had thought you were talking about keys in, say, a `dict` which would then be dropped when converted to a `Namelist`.

But it seems like you would like these `_`-leading metadata fields to actually become valid variables in the namelist which hang around in some way, with the one exception being that they do not appear in the final output.

Have I got that right?

I am a little less confident about this change.  It might be helpful to know how you are using these metadata keys in your work.

**Comment by MuellerSeb** [comment]
No, I would like them to be dropped, when written to file. Beside that you are right, I'd like to have my own meta-data keywords that are marked by starting with "_".

**Comment by MuellerSeb** [comment]
Sorry, I read again, what you wrote, and you got it totally right.

What we want to do:
We would like to store namelists as part of workflow configurations in a json like format. Since the dict representation of f90nml works totally fine with the json package of python, we wanted to directly use this. In addition we wanted to add doc-strings to each namelist entry, valid ranges and value types. These should be stored as meta-data similar to start index handling in f90nml.

When I read that keys starting with "_" are ignored, I thought it would be fine to do it that way.

**Comment by marshallward** [comment]
I think something like this could be valuable, and I'd like to help find a solution.

Ideally, we probably should only allow `Namelist` keys which could exist in the actual namelist.  If I strictly follow that assertion, then it would not make sense to create special rules for invalid keys.  The correct thing to do would be to reject the keys!

But as you know, it is already possible to add them, so we are already in an impure state.  Given the current situation, ignoring such keys in the `write()` call is an easy (and perhaps even justifiable) solution.

I think a better solution however might be to support some sort of "meta" field (`.doc`, `.attr`, `.meta`?), which explicitly tags this information as supplemental, and not to be parsed as namelist data.  A very hypothetical example is a future format which does not support keys with leading underscores.

I could see either one working.  But allowing and not writing the `_`-leading keys could disappear in the future.  The second seems more sustainable.

**Comment by marshallward** [comment]
Not sure where to go with this... should we close?  Was it just a misunderstanding of the role of `_`?

As tempted as I am to follow up and prevent keys with leading `_` characters, would that disrupt your own work?

**Comment by marshallward** [comment]
Closing this issue.  But please re-open if you're interested in some kind of method for user-defined metadata (either by clobbering the `_*` namespace or a more rigorous solution).
