### ISSUE TITLE
Bug reading mixed lists in version 1.4.0

### ISSUE THREAD

**Issue by rhfogh** [marshallward/f90nml#141]
We rely on f90nml to read our input and configuration files (thanks!), but after upgrading to the recent version 1.4.0, files that used to work are triggering an error.

Specifically, reading an nml file with the following structure:
&list_1
val1=1.0
/
&list2
val2=2.0
/
&list2
val2=2.0
/
&list_1
val1=1.0
/

causes the following error:

>>> f90nml.read("testbreaks.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/.mc38/lib/python3.8/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "[...]/.mc38/lib/python3.8/site-packages/f90nml/parser.py", line 281, in read
    return self._readstream(nml_file, nml_patch)
  File "[...]/.mc38/lib/python3.8/site-packages/f90nml/parser.py", line 424, in _readstream
    nmls.add_cogroup(g_name, g_vars)
  File "[...]/.mc38/lib/python3.8/site-packages/f90nml/namelist.py", line 620, in add_cogroup
    self.create_cogroup(lkey)
  File "[...]/.mc38/lib/python3.8/site-packages/f90nml/namelist.py", line 606, in create_cogroup
    grp = self.pop(key)
KeyError: 'list2'

Attached testbreaks.txt (that triggers the error when read) and six variant files (testworks1-6.txt) that read correctly.

[testbreaks.txt](https://github.com/marshallward/f90nml/files/8790797/testbreaks.txt)
[testworks6.txt](https://github.com/marshallward/f90nml/files/8790798/testworks6.txt)
[testworks5.txt](https://github.com/marshallward/f90nml/files/8790799/testworks5.txt)
[testworks4.txt](https://github.com/marshallward/f90nml/files/8790800/testworks4.txt)
[testworks3.txt](https://github.com/marshallward/f90nml/files/8790801/testworks3.txt)
[testworks2.txt](https://github.com/marshallward/f90nml/files/8790802/testworks2.txt)
[testworks1.txt](https://github.com/marshallward/f90nml/files/8790803/testworks1.txt)

Reading the same file in f90nml version 1.3.1 gives the correct result:
>>> print(f90nml.read("testbreaks.txt"))
Namelist([('list_1', [Namelist([('val1', 1.0)]), Namelist([('val1', 1.0)])]), ('list2', [Namelist([('val2', 2.0)]), Namelist([('val2', 2.0)])])])

Versions:
>>> f90nml.__version__
'1.4'
freshly installed with miniconda on our release computer, and copied to the test computer.

>>> print(sys.version)
3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0]

Linux version 5.3.18-150300.59.68-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Wed May 4 11:29:09 UTC 2022 (ea30951)

A fix would be greatly appreciated.

**Comment by marshallward** [comment]
I believe this has been fixed recently.  Can you test this branch?

https://github.com/marshallward/f90nml/tree/constructor_empty_list

**Comment by marshallward** [comment]
For the sake of logging:

There was an bug in the naming of the internal keys, resulting in some repeated groups using the repeated naming convention, and others erroneously bypassing it by using the original, unhashed key.  Most cases appear to work, but a few permutations would detect the problem.

Discussed a bit more in #139.

**Comment by rhfogh** [comment]
The constructor_empty_list branch does indeed work. Thanks very much for the quick response.

Just so we can get our nightly build system synchronised properly (we are sticking with branch 1.3.1 for now so we are in no hurry) when would you expect the updated branch to make it onto PIP?

**Comment by marshallward** [comment]
I was about to put this in until seeing this report :sweat_smile: so I will do the bugfix update today.

**Comment by marshallward** [comment]
Sorry, I found a few other minor issues while preparing the tests, so I've been fixing those up before doing another release.

Confession time: I knew this feature had potential problems, but the only way to get feedback is to do a release. :laughing: 

It's possible that I could wrap this up by the end of the day, but if not then no more than another day or two.

**Comment by rhfogh** [comment]
Not  to worry for our sake. We are fully OK with version 1.3.1, and we know that 'RSN' there will be an updated version, so  just take the time it needs. I just wanted to know the rough number of months, for general planning purposes, and I know that now (<= 1). In fact the level of service is very much appreciated.
