### ISSUE TITLE
f90nml without the -p option makes the transformed namelist unusable

### ISSUE THREAD

**Issue by fthomas61** [marshallward/f90nml#154]
Here is a namelist which I am trying to change with f90nml:

```
# cat namelist.input 
 &time_control
 run_days                            = 5,
 start_year                          = 2020, 2020, 2020, 2020,
 start_month                         = 06, 06, 06, 06,
 input_from_file                     = .true.,.true.,.true.,true.,
 history_interval                    = 60,  60,   60,  60,
 frames_per_outfile                  = 1, 1, 1, 1,
 restart                             = .false.,
 restart_interval                    = 1440,
 override_restart_timers             = .false.,
 write_hist_at_0h_rst                = .true.,
 /
```

Changing this namelist without the -p option gives:

```
# f90nml namelist.input -g time_control -v nproc_x=3 
&time_control
    run_days = 5
    start_year = 2020, 2020, 2020, 2020
    start_month = 6, 6, 6, 6
    input_from_file = .true., .true., .true., 'true.'
    history_interval = 60, 60, 60, 60
    frames_per_outfile = 1, 1, 1, 1
    restart = .false.
    restart_interval = 1440
    override_restart_timers = .false.
    write_hist_at_0h_rst = .true.
    nproc_x = 3
/
```
Note the end commas are gone (not too bad), the formatting of start_month is gone (not too bad), but the input_from_file array is complete garbage and makes the namelist unusable.

Changing this namelist with the -p option is fine:
```
# f90nml namelist.input -g time_control -v nproc_x=3  -p
 &time_control
 run_days                            = 5,
 start_year                          = 2020, 2020, 2020, 2020,
 start_month                         = 06, 06, 06, 06,
 input_from_file                     = .true.,.true.,.true.,true.,
 history_interval                    = 60,  60,   60,  60,
 frames_per_outfile                  = 1, 1, 1, 1,
 restart                             = .false.,
 restart_interval                    = 1440,
 override_restart_timers             = .false.,
 write_hist_at_0h_rst                = .true.,
     nproc_x = 3
/
```

We are using:
```
# f90nml --version
f90nml 1.4.3

with Python 3.10.2
```

**Comment by marshallward** [comment]
Just confirming: the error is that the final value was turned into a string, right?  All of the other values are correcT?  If so, then I can replicate this.

(For better or worse, the reformatting is by design, so the other behavior is as expected.)

**Comment by marshallward** [comment]
Ah... your final value has an unusual syntax: `true.` rather than `.true.`.

If one consuls The Holy Language Standard (F2018), it says that anything starting with a `T` (or `.T`) is interpreted as a logical `.true.`, so that may be why it worked for you despite the different form.

Certain users objected to this behavior because they would use non-delimited strings, which occasionally started with a `T`.  They did not like these being interpreted as `.true.`, so the default behavior is to interpret them as strings.

There is a flag in the parser, `strict_logical`, which can be set to `False`, and will correctly interpret this as a logical.  However, I don't know if this is accessible from the command line.  I will look into it and follow up later today.

**Comment by marshallward** [comment]
(as for why the `-p` worked, it tries to preserve the original syntax of the file.  So it is writing `true.` as a non-delimited string, which happens to look identical in this case.

**Comment by fthomas61** [comment]
There was a mistake in the original namelist. Fortran was fine with this mistake but not f90nml. I'll fix my original namelist. Thanks.

**Comment by marshallward** [comment]
I think this is the relevant bit:
> The standard form of the input field consists of optional blanks, optionally followed by a period, followed by a T for true or F for false. The T or F may be followed by additional characters in the field, which are ignored. If the input field does not have the standard form, and is not acceptable to the processor, an error condition occurs.
