### ISSUE TITLE
f90nml does not parse WRF namelist files at all 

### ISSUE THREAD

**Issue by wxguy** [marshallward/f90nml#155]
Here is the sample of WRF namelist file (`namelist.wps` is the file name) I am trying to load using f90nml:

```
&share
    wrf_core = 'ARW'
    max_dom = 2
    start_date = '2019-09-04_12:00:00', '2019-09-04_12:00:00'
    end_date = '2019-09-06_00:00:00', '2019-09-04_12:00:00'
    interval_seconds = 10800
/

&geogrid
    parent_id = 1, 1
    parent_grid_ratio = 1, 3
    i_parent_start = 1, 53
    j_parent_start = 1, 25
    e_we = 150, 220
    e_sn = 130, 214
    geog_data_res = 'default', 'default'
    dx = 15000
    dy = 15000
    map_proj = 'lambert'
    ref_lat = 33.0
    ref_lon = -79.0
    truelat1 = 30.0
    truelat2 = 60.0
    stand_lon = -79.0
    geog_data_path = '/glade/work/wrfhelp/WPS_GEOG/'
/

&ungrib
    out_format = 'WPS'
    prefix = 'FILE'
/

&metgrid
    fg_name = 'FILE'
/
```

Here is the simple test code I tried:

```
import f90nml

namelist = '/home/sundar/wrf_install/WPS/namelist.wps'
nml = f90nml.read(namelist)
print(nml)
```

Expected outcome (sample):

```
nml = {
    'share': {
        'share': 'ARW',
        'share': 1,
        'start_date': '2019-09-04_12:00:00',
        'end_date':  '2019-09-06_00:00:00',
        'interval_seconds': 10800
    }
}
```

But here is what I got (just same as original file content):

```
&share
    wrf_core = 'ARW'
    max_dom = 2
    start_date = '2019-09-04_12:00:00', '2019-09-04_12:00:00'
    end_date = '2019-09-06_00:00:00', '2019-09-04_12:00:00'
    interval_seconds = 10800
/
.
.
.
```

Is it intended outcome of the module or am I doing something wrong?

**Comment by marshallward** [comment]
Can you check the version? I am seeing the correct output.

**Comment by marshallward** [comment]
Let me clarify what I have done, just to make sure we are checking the same thing.

I assume your file `namelist.wps` is the same as your first code block.  If I load this using your example in the second code block, this is what I see:
```
&share
    wrf_core = 'ARW'
    max_dom = 2
    start_date = '2019-09-04_12:00:00', '2019-09-04_12:00:00'
    end_date = '2019-09-06_00:00:00', '2019-09-04_12:00:00'
    interval_seconds = 10800
/
...
```
This matches the input file, which is what I meant by "correct".  

But I cannot recognize this:
```
nml = {
    'share': {
        'share': 'ARW',
        'share': 1,
        'start_date': '2019-09-04_12:00:00',
        'end_date':  '2019-09-06_00:00:00',
        'interval_seconds': 10800
    }
}
```
I am not sure what it's supposed to represent.  For example, why is `share` repeated.  Have you modified `nml` and are trying to print the output?

**Comment by wxguy** [comment]
> Let me clarify what I have done, just to make sure we are checking the same thing.
> 
> I assume your file `namelist.wps` is the same as your first code block. If I load this using your example in the second code block, this is what I see:
> 
> ```
> &share
>     wrf_core = 'ARW'
>     max_dom = 2
>     start_date = '2019-09-04_12:00:00', '2019-09-04_12:00:00'
>     end_date = '2019-09-06_00:00:00', '2019-09-04_12:00:00'
>     interval_seconds = 10800
> /
> ...
> ```
> 
> This matches the input file, which is what I meant by "correct".
> 
> The literal contents of `share` are:
> 
> ```
> >>> nml['share']
> Namelist([('wrf_core', 'ARW'), ('max_dom', 2), ('start_date', ['2019-09-04_12:00:00', '2019-09-04_12:00:00']), ('end_date', ['2019-09-06_00:00:00', '2019-09-04_12:00:00']), ('interval_seconds', 10800)])
> ```
> 
> But I cannot recognize this:
> 
> ```
> nml = {
>     'share': {
>         'share': 'ARW',
>         'share': 1,
>         'start_date': '2019-09-04_12:00:00',
>         'end_date':  '2019-09-06_00:00:00',
>         'interval_seconds': 10800
>     }
> }
> ```
> 
> I am not sure what it's supposed to represent. For example, why is `share` repeated? Have you modified `nml` and are trying to print the output? Or is this actually what you are seeing, rather than the "correct" output (as I have defined it)?

Thank you for your clarification and you are correct. The repeated `share` was a typo from my side. 

Doubt came because of misinterpretation of the official documentation which says `which would point nml to the following dict`. This I understood as `nml` should also print `dict` which is not the case here. May be you may want to clarify in your documentation that printing of `nml` object will not print `dict`.

**Comment by marshallward** [comment]
Thank you for the suggestion.  You are correct that it does not output a `dict`, but rather a `Namelist` which is a subclass of `OrderedDict`.  Most likely, the line in question was written during the early days of the project when the output was a `dict`.

In fact, even the use of "point" is perhaps a bit off-putting.

Perhaps a better statement 
> which creates a `Namelist` that is equivalent to the following `dict`


----

Getting back to your issue, the `Namelist()` output should be correct.  If you can confirm that it is correct, then I think we can close this issue.  If you want to submit an amedment to the documentation, then it would be welcome.

**Comment by wxguy** [comment]
I can confirm that `Namelist()` output is correct from my side as well. 

Regarding the pull request, will work when I get free time.

Closing the issue now.
