### ISSUE TITLE
conda-forge package available

### ISSUE THREAD

**Issue by aidanheerdegen** [marshallward/f90nml#164]
There is now a conda-forge feedstock and package available which is kinda cool

https://github.com/conda-forge/f90nml-feedstock

In case you want to mention it as an install option in the README or docs.

**Comment by marshallward** [comment]
Thanks for bringing this up.  I have come across it, but I don't use Conda and I also don't know if this repo represents the best or proper way to bring f90nml into a conda environment.

But if you know more about it and want to suggest a revision to the README, then I could add it.

**Comment by jacobwilliams** [comment]
FYI: conda is how I've installed f90nml for years and it works great.

**Comment by aidanheerdegen** [comment]
We've also been using `conda` for ages and find it a great solution in many cases.

As far as `conda` goes, a `conga-forge` is pretty much the gold standard for creating and distributing open source python packages.

I can have a go at a PR to update the README.
