### ISSUE TITLE
get not using __getitem__

### ISSUE THREAD

**Issue by ghislainp** [marshallward/f90nml#19]
I have a problem using patch and namelist with upercase.
It's because namelist defines __getitem__ to properly handle lower/uppercase but the code in the paser uses the get method (line 131) which does not call __getitem__.
I don't know why get does use __getitem__ nor if this applies to any python version... I'm using 2.7.10

Either redefine the get method in namelist obj or use
  
grp_patch = nml_patch[g_name] if g_name in nml_patch else {}

**Comment by marshallward** [comment]
Yep, confirmed.  If the namelist patch group name is not lowercase, then it won't match the (modified) lowercase name in the `Namelist`.

Thanks very much for finding the bug and providing the explanation.

I'll patch something in today.

**Comment by marshallward** [comment]
It looks like we can fix this by replacing `g_name` with `g_name.lower()`.

A better solution would be to fix `Namelist` to handle `get` properly, but this does not look very straightforward (but maybe it's not too much work?).

I've pushed a change that should hopefully fixed your problem, and have also added a case sensitivity patch test case.

**Comment by marshallward** [comment]
I'll assume this is fixed unless I hear otherwise.

Thanks again for the feedback.
