### ISSUE TITLE
Obscure real formats

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#23]
So here's a good one:

I have some namelists with double variables that are formatted like this: `blah= 0.1000000000000000+100,`
This value is really `0.1D+100`, but I think the format statement that originally wrote it didn't have enough digits to put the `E` maybe? However, Intel reads in this value just fine. `f90nml` reads it as a string: `blah= '0.1000000000000000+100'`. The code I have now outputs it properly, but I want to be able to read the older files too.

Would it be possible to include a case where a number with a format like this could be read in properly as a value?

This is a terrific library btw. I'm finally starting to use it for production work. Except for this weird edge case, It is working beautifully!

**Comment by marshallward** [comment]
Yeah, interesting, gfortran, Intel fortran, and PGI fortran were all able to read it, with the correct value (within rounding). Freaky! 

It doesn't seem to be addressed in the standard (i.e. I don't think this is valid Fortran), but if three separate compilers support it then it might as well be treated as correct.

I've just put in a patch which should correctly handle those cases , and didn't seem to break anything else.

Thanks once again!  I'm glad that you've found it useful :) I owe you thanks for identifying most of the derived type bugs.

**Comment by marshallward** [comment]
Scratch that, still buggy...

**Comment by marshallward** [comment]
This should now be resolved by ec1885960f2014acfb25c2bb974f2526c959e588
