### ISSUE TITLE
Appending to existing file

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#27]
I was wondering if a good option for `write` might be to allow for appending to an existing file? This would be an easy way to put some comments in the file first if you wanted, and then write the namelist.

**Comment by ExpHP** [comment]
Note: If #25 happens, this use-case would be possible via:

    with open('some.nml', 'a') as f:
        f90nml.write(nml, f)

**Comment by jacobwilliams** [comment]
Yes, I agree. That is the best way to do it.

**Comment by marshallward** [comment]
Seems like this should be working now, thanks to @ExpHP 's  patch.  Is that right?

My interpretation is to turn this file

    ! I am a comment

into this file:

    ! I am a comment
    &some_nml
        x = 1
    /

**Comment by jacobwilliams** [comment]
Yes, it works great! Thanks!

### nml.txt:
```
&sample_nml
   x = 1
/
```

### code:

```python
import f90nml

nml = f90nml.read('nml.txt')

with open('nml2.txt','w') as f:
    f.write('! I am a comment\n')
    nml.write(f)
```

### nml2.txt:
```
! I am a comment
&sample_nml
    x = 1
/
```
