### ISSUE TITLE
String-based APIs

### ISSUE THREAD

**Issue by ExpHP** [marshallward/f90nml#28]
Broken off from #25.

Add string versions of read, patch, and write (under different names), comparable to `json.loads` or `xml.etree.fromstring`.  With the file APIs in place, it should be possible to write all of these as simple wrappers using `StringIO`.

**Comment by ExpHP** [comment]
P.S. This time I am not already secretly working on a PR in the background, so you don't have to worry about that in case you'd rather handle things! =P  (though on the offchance you would like one, I can gladly oblige!)

**Comment by marshallward** [comment]
It should just be two lines, since `shlex` accepts a string as an input.

For example, this seems to already work:

    from f90nml import Parser
    p = Parser()
    nml = p.readstream('&nml x=1 /', {})

I think it's just a matter of choosing an API.  `reads` seems OK to me.  It could be as simple as renaming `readstream` to `reads` and setting the default `nml_patch` value to `{}`.

**Comment by ExpHP** [comment]
TBH I think it would be a little silly then that the implementation of `read` would be calling `reads` with file objects! (also note that shlex uses StringIO internally, so there is no performance to gain.)

**Comment by marshallward** [comment]
Because file objects could be fed directly to `reads` rather than `read`?

**Comment by ExpHP** [comment]
Moreso because I would be surprised that `reads` can take a file!

On the other hand, however, it does kind of open up an alternate possible way of laying out the API.  Instead of a file+path method and a string method, there could be a string+file method (`reads`) and a path method (`read`).

**Comment by marshallward** [comment]
I am ok with this.  Maybe people can interpret the "s" as "[s]treamable file object or [s]tring".

Though I do like the idea of `read` working for file objects.  It really should be the default behaviour.  Expecting filepaths was probably a poor decision from the beginning.

I'll think on it over the weekend (I'll may be without internet, maybe that will help?).

**Comment by marshallward** [comment]
This has probably been more or less resolved by #76 due to the new tokenizer and `reads` functions, so I can finally close this.

I appreciated your feedback on this issue, so feel free to add anything or re-open either of these issue if you like.
