### ISSUE TITLE
Numpy types

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#29]
I was wondering if it would be possible to update the representation function in `namelist.py` to support numpy types? Your code is not using them, but I have a use case where I'm using your code to read a namelist, and then I have APIs to allow manually adjusting some of the values. I'm allowing numpy values if the user wants to pass them in, but your code is only looking for `bool`, `float`, etc., so it is crashing in `write()` with a ValueError.

I think it could be done without creating a numpy dependency in your code, since the numpy types are instances of the default types. For example:

```python
>>> import numpy as np
>>> a = np.float64(1.1)
>>> type(a)
<type 'numpy.float64'>
>>> isinstance(a,float)
True
```

What do you think?

**Comment by marshallward** [comment]
Yeah, I agree with this.  Requiring the primitive types is too restrictive.  And I was probably being too clever using the "types as dict keys" approach.  Switching it (back) to chained if-statements with `isinstance` should hopefully resolve this.

I wonder if it's worth going a step further and supporting numpy arrays, e.g.

    nml = {'nml': {'x': np.array([1, 2, 3])}}
    f90nml.write(nml, 'out.nml')

although I don't know an easy way to reinterpret them as lists, or maybe as iterators.

**Comment by jacobwilliams** [comment]
Yes, for completeness, that would be great too, if it's possible.

**Comment by marshallward** [comment]
BTW, I noticed that `numpy.float64` is an instance of `float`, but `numpy.int64` is not an instance of `int`.  Does this cause any problems?

**Comment by marshallward** [comment]
Nevermind, this seems solvable by testing against the `numbers` module.

**Comment by marshallward** [comment]
This should be working on master branch now.

**Comment by jacobwilliams** [comment]
Thanks! Works great!
