### ISSUE TITLE
Write bug in v0.20

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#40]
I'm getting an odd bug when trying the write the following namelist:

```
 &a
 b%c_d_E(1)%ID = 1,
 b%c_d_E(2)%ID = 2,
 /
```

Code is:

```python
    import f90nml
    data = f90nml.read('test.nml')
    with open('test_RESAVED.nml','w') as f:
        data.write(f, force=True)
```
Error message is:

```python
Traceback (most recent call last):
  File "test.py", line 309, in <module>
    data.write(f, force=True)
  File "C:\Anaconda3\lib\site-packages\f90nml\namelist.py", line 232, in write
    self.write_nmlgrp(grp_name, grp_vars, nml_file)
  File "C:\Anaconda3\lib\site-packages\f90nml\namelist.py", line 253, in write_nmlgrp
    for v_str in self.var_strings(v_name, v_val, v_start=v_start):
  File "C:\Anaconda3\lib\site-packages\f90nml\namelist.py", line 302, in var_strings
    v_strs = self.var_strings(v_title, f_vals, v_start=v_start_new)
  File "C:\Anaconda3\lib\site-packages\f90nml\namelist.py", line 313, in var_strings
    i_s = v_start[::-1][len(v_idx)]
TypeError: 'NoneType' object is not subscriptable
```
Oddly, when I change `c_d_E` to `c_d_e`, it works fine.

I just updated to the latest release using pip. I've been able to read variables like this before, so something has changed.

**Comment by marshallward** [comment]
I can reproduce this, and I think I understand the problem.

The start index is now tracked within the namelist, but it's just a standard `dict` with case-sensitive keys, whereas the `Namelist` object converts everything to lowercase.  So the `b` namelist's `start_index` contains `c_d_E` but it is looking for `c_d_e`.

I'm not sure the best solution, and I'm not sure why it didn't default to 1 (which would have been a more subtle error anyway), but I will try to fix this asap.

**Comment by jacobwilliams** [comment]
It fixed that one, but now I'm getting a read error for this one:

```
&a
 b%c(1)%id = 1,
 b%c(2)%id = 2,
 b%c(3)%id = 3,
 b%c(4)%id = 4,
 b%c(4)%d%e(1) = 10,
 b%c(4)%d%e(2) = 11,
/
```

```python
>>> data = f90nml.read('test.nml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\git\f90nml\f90nml\__init__.py", line 57, in read
    return parser.read(nml_path)
  File "C:\git\f90nml\f90nml\parser.py", line 108, in read
    return self.readstream(nml_file, nml_patch)
  File "C:\git\f90nml\f90nml\parser.py", line 173, in readstream
    patch_nml=grp_patch)
  File "C:\git\f90nml\f90nml\parser.py", line 316, in parse_variable
    patch_nml=v_patch_nml)
  File "C:\git\f90nml\f90nml\parser.py", line 316, in parse_variable
    patch_nml=v_patch_nml)
  File "C:\git\f90nml\f90nml\parser.py", line 310, in parse_variable
    parent[v_name] = v_parent
TypeError: list indices must be integers or slices, not str
```
The case doesn't seem to matter in this instance.

**Comment by marshallward** [comment]
Looks like you found the secret bug (parser.f90, line 310 or so):

    # FIXME: If we were in an index (v_idx != None) then v_parent is
    # incorrectly set as the list of dicts rather than the respective
    # dict (which must somehow be deduced from v_idx at some later
    # stage)

    # This is not causing any errors, but the parent value is nonsense
    # and could break something in the future.

Looks like it did break something in the future... I will have a look today.

**Comment by marshallward** [comment]
I've added a fix that now passes the element (`b%c(4)`) as the parent for new elements (`b%c(4)%d`), rather than the entire list (`b%c(:)`).  It seems to be working for me.  This should also let me clean up a few poorly written sections.

The new implementation is still kind of cruddy, but it should eliminate this bug.

**Comment by jacobwilliams** [comment]
I'm getting another case error with this one:
```fortran
 &A
 B%C = 1,
 B%D(1)%ID = 2,
 /
```

code is:

```python
import f90nml
data = f90nml.read('test.nml')
with open('test_resaved.nml','w') as f:
    data.write(f, force=True)
```
error is:

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\git\f90nml\f90nml\namelist.py", line 232, in write
    self.write_nmlgrp(grp_name, grp_vars, nml_file)
  File "C:\git\f90nml\f90nml\namelist.py", line 253, in write_nmlgrp
    for v_str in self.var_strings(v_name, v_val, v_start=v_start):
  File "C:\git\f90nml\f90nml\namelist.py", line 302, in var_strings
    v_strs = self.var_strings(v_title, f_vals, v_start=v_start_new)
  File "C:\git\f90nml\f90nml\namelist.py", line 313, in var_strings
    i_s = v_start[::-1][len(v_idx)]
TypeError: 'NoneType' object is not subscriptable
```

If it's all lowercase, it works. Also, if the ` B%C = 1,` variable isn't there, it also works for either case.

Sorry I keep finding bugs! It's what I do. :)

**Comment by marshallward** [comment]
It's always nice to see bug reports, much better than the ones that never get reported :).  Or even worse, ranted about on private blogs or Twitter! 

Looks like an namelist was being created and populated with data from an old namelist, but its `start_index` was not being copied.  Should be OK now?

**Comment by jacobwilliams** [comment]
There's still a case problem somewhere. For this one:
```
 &A
 B%C(1)%ID = 1,
 B%C(2)%ID = 2,
 /
```
When I do the read and then write it leaves out the first one:
```
&a
    b%c(2)%id = 2
/
```

**Comment by marshallward** [comment]
OK, just another case problem.  I've fixed this, but I've discovered that the previous fix was a bit volatile, will look into it now.

**Comment by marshallward** [comment]
Actually, it seems like fixing the fourth example also fixed the third... let's leave it at that.

Could you try it out now?

**Comment by jacobwilliams** [comment]
Another case one (I think), when we start with non-1 indices:
``` 
&a
 B%C(5)%D = 1,
 B%C(5)%E = 2,
 B%C(5)%F = 3,
 B%C(5)%G = 4,
 B%C(5)%H = 5,
 /
```
Save/resave:
```
&a
    b%c(1)%d = 1
    b%c(2) = ,
    b%c(3) = ,
    b%c(4) = ,
    b%c(5)%e = 2
    b%c(5)%f = 3
    b%c(5)%g = 4
    b%c(5)%h = 5
/
```

**Comment by marshallward** [comment]
Yep, start index key search was not case-insensitive.  Should be working now (...?).

**Comment by jacobwilliams** [comment]
Thanks so much for being so responsive!

I think I've got one more though. When the indices are non-contiguous,

```
&A
 B%C(1)%A = 1,
 B%C(4)%A = 1,
 B%C(8)%A = 1,
/
```
read/write:
```
&a
    b%c(1)%a = 1
    b%c(2) = ,
    b%c(3) = ,
    b%c(4)%a = 1
    b%c(5) = ,
    b%c(6) = ,
    b%c(7) = ,
    b%c(8)%a = 1
/
```

**Comment by marshallward** [comment]
I can fix this by just not printing Null entries in the list, which seems to work fine.

But maybe there is some use case for explicitly setting a null value?  If that's the case, then it would be necessary to distinguish the explicit nulls from the implicit ones (i.e. the "gaps" between the explicit indexed values).

(My guess is most compilers would be ok with the null entries.)

I am leaning towards not printing out null values though.

**Comment by jacobwilliams** [comment]
Yes, not printing the null entries is probably the way to go:
```
&a
    b%c(1)%a = 1
    b%c(4)%a = 1
    b%c(8)%a = 1
/
```
All the compilers I've dealt with will leave those elements as is. In fact, I'm actually making use of that feature. I don't know what they would do with the entries like `'b%c(2) = ,'`. I can check. I was worried if it was a string array it might blank those elements.

**Comment by marshallward** [comment]
Actually it looks like I used to have this turned on, and disabled it because my coverage tool says that it could never be called!  I've restored it now.

It looks like this particular case is restricted to lists of derived types, so none of the scenarios described above (e.g. strings reset with null values) should be a problem.

**Comment by jacobwilliams** [comment]
Well, I can't find anything else to complain about. Thanks!!

**Comment by marshallward** [comment]
Thanks for reporting all those bugs.  I figured that the generalised first index change would break a lot of things, and it looks like you found most of them!

I'll throw these examples into a test case today.

**Comment by jacobwilliams** [comment]
Any chance of getting an 0.21 release that includes these fixes?

**Comment by marshallward** [comment]
Sorry about that, I had hoped to look into that 72+ character variable name
bug, but never got a chance.  I've done a version update containing the
derived type changes though and sent it to pypi
