### ISSUE TITLE
Command line interface and 1.0 roadmap

### ISSUE THREAD

**Issue by marshallward** [marshallward/f90nml#46]
This is less of an issue and more of an annoucement that `f90nml` now includes a command line tool for modifying namelists through the command line.

The tool is not yet in `master`, but is available in the `cli` branch.

Basic usage is as follows:
* `f90nml <input>` will convert <input> to a namelist if possible.  It "detects" this by extension.  Currently only JSON and YAML (if installed) are supported.  The output is streamed to stdout.
* `f90nml <input> <output>` will save the output to the target file.  If the extension is `.yaml` or `.json` then it will convert the file.
* `f90nml -g <grp> -s var1=val1<output>` will either add or replace the variable `var1` in namelist `grp` with value `val1`
* `f90nml -p ...` will apply the change as a patch to an existing file, preserving comments and layout.

The (very minimal) runscript is in the `bin` directory, but will be useable after a `python setup.py install`.

I have been pushing out lots of 0.x releases for many years now, but I always had two major goals before considering a 1.0 release.  The first was a command line interface, and the second was a native Python tokenizer, which could be improved over time.  Now that those two goals have been met, I'd like to set a 1.0 release soon.

Before doing that, I'd like to get feedback on the command line tool, which still has many potential issues, but would also like to get a request for content in 1.0 before releasing.

Also, any suggestions for improving communication (mailing list, slack, etc) would be welcome.

**Comment by jacobwilliams** [comment]
Awesome! Will test the `cli` feature soon. Great idea.

**Comment by marshallward** [comment]
I've moved the CLI into master, though not yet documented.

@aidanheerdegen @nicjhan @aekiss @MartinDix Would be good to get feedback from you guys as well.

**Comment by rgieseke** [comment]
This looks very cool! How will the `-p` syntax look like?

Also, have you considered allowing stdout output of the JSON and YAML? This would be helpful for development and in combination with other tools, like [jq](https://stedolan.github.io/jq/).

**Comment by marshallward** [comment]
Normally `-p` would preserve any comments or whitespace in the namelist.  But it looks like I have not actually implemented it yet, so it does nothing :).

**Comment by rgieseke** [comment]
Very nice, I misunderstood the `-p` flag, I had thought it would include what `-s` does. 
The `-f` option works well!

**Comment by marshallward** [comment]
With the 0.23 release and the latest commit (a4a2a73eeafad65e29706f44a68ae9d47bceddd6) I will probably fix the features and do a 1.0 release very soon, probably after sitting on it for a week or so and putting in the final few tests.

**Comment by marshallward** [comment]
1.0 is now release, closing this.

**Comment by aekiss** [comment]
Hi Marshall

Congrats on the 1.0 release :)

I tried to install it on my mac using pip 9.0.1 but I get this

pip install --upgrade f90nml
Collecting f90nml
  Downloading f90nml-1.0.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 391kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ch/j30c0xth8v50z6008k8zh6fr0000gn/T/pip-build-r4ggdp0m/f90nml/setup.py", line 27, in <module>
        import tests.test_f90nml
    ImportError: No module named 'tests.test_f90nml'



    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ch/j30c0xth8v50z6008k8zh6fr0000gn/T/pip-build-r4ggdp0m/f90nml/

On 29 Jan 2018, at 1:37 pm, Marshall Ward <notifications@github.com<mailto:notifications@github.com>> wrote:


1.0 is now release, closing this.

**Comment by marshallward** [comment]
I did rename `test` to `tests`, maybe that is the issue here?

**Comment by marshallward** [comment]
Actually no, I am reproducing this... will have a look.

**Comment by marshallward** [comment]
Looks like the `__init__.py` for tests did not make it into the build, yikes... should be fixable soon.

**Comment by marshallward** [comment]
So much for 1.0... 1.0.1 is updated with the included test scripts, which are now integrated into setup.py (hence the error, and the error in the MANIFEST).

Hopefully working now.

**Comment by aekiss** [comment]
Thanks Marshall, it's installing fine for me now.
