### ISSUE TITLE
Variables with mix of individual and repeated values

### ISSUE THREAD

**Issue by fizzysister** [marshallward/f90nml#47]
Hi, I'm having problems when reading variables for which some, but not all, of the elements are listed using repeat factors. Any values that are read after a repeat factor are also being repeated.

For example, with a namelist file `namelist.nml`, containing the namelist

```
&my_namelist
    foo = 3*1,2,3,4
    bar = 3*1,2*2,3
/
```

Reading it with
```
import f90nml

filename='namelist.nml'
namelist = f90nml.read(filename)
```

The variables in the dicts have too many copies of the values that come after the repeat factors
```
>>> namelist['my_namelist']['foo']
[1, 2, 2, 2, 3, 3, 3, 4, 4, 4]
>>> namelist['my_namelist']['bar']
[1, 1, 1, 2, 2, 3, 3]
```

It looks like the repeat factor (n_vals) is being stored when reading the next value in the list.

**Comment by marshallward** [comment]
Thanks, I've tried to fix this in the latest commit (a1a62cdb4292f615c63f7e5d1a46de4c762ff354), can you give it a try?

**Comment by fizzysister** [comment]
Great, that looks to be working correctly to me. Thanks!

**Comment by marshallward** [comment]
Great, thanks again for the report!

**Comment by marshallward** [comment]
Just noticed that I put these changed in the `cli` branch, not `master`... will update that now.
