### ISSUE TITLE
Possible bug report for multiple dimension arrays

### ISSUE THREAD

**Issue by zhucaoxiang** [marshallward/f90nml#48]
Hi, this is a useful tool. I found a possible bug when trying to read multiple dimension arrays.
Here is the example namelist file:
```
&TEST
  a = '12abc'
  ltest = 1
  RBC(0,0) =   1.33100000000000E+00     ZBS(0,0) =   0.00000000000000E+00
  RBC(9,6) =  -8.49639241991135E-05     ZBS(9,6) =  -1.31291865009956E-04
/
```
What we get by using `f90nml.read`:
```
Namelist([('test', Namelist([('a', '12abc'), ('ltest', 1), ('rbc', [[1.331], [], [], [], [], [], [None, None, None, None, None, None, None, None, None, -8.49639241991135e-05]]), ('zbs', [[0.0], [], [], [], [], [], [None, None, None, None, None, None, None, None, None, -0.000131291865009956]])]))])
```
Apparently, the array data is not correct. Would you pleas help fix the bug? Or if you can point out which part is related to this function. I can help contribute.

**Comment by zhucaoxiang** [comment]
Exactly! Right now, it's not convenient to export the whole array, since the dimension is not standard and there are empty or "None" terms, which I think it would be better with zero value.

**Comment by marshallward** [comment]
Well I definitely cannot put zero values in.  Partly because the compiler may or may not initialise them to zero, and partly because reading a namelist can override existing values, so we should not be adding information to the namelist entry.

It might be worth filling in `None` values on these larger arrays, although I'm a bit reluctant to make them bigger for the sake of convenience.  This could be an optional setting.

**Comment by zhucaoxiang** [comment]
I agree. Thanks for your kind reply and effort. You can close this issue now.

**Comment by marshallward** [comment]
I'll leave it open for a bit longer; resizing the lists is not a bad idea, even if only optionally.  I'll think about how to make multidimensional arrays more convenient, e.g. something numpy can understand.

**Comment by zhucaoxiang** [comment]
That would be much more convenient! Thanks!

**Comment by marshallward** [comment]
The latest commit (a4a2a73eeafad65e29706f44a68ae9d47bceddd6) should have something that works for you.  To try it out:

```
import f90nml
import numpy

p = f90nml.Parser()
p.dense_arrays = True
nml = p.read('md.nml')   # Or whatever the filename was

rbc_in = nml['test']['rbc']
rbc = numpy.array(rbc_in)
```

**Comment by zhucaoxiang** [comment]
Fantastic. I will check this later. Thank you very much.

**Comment by marshallward** [comment]
Going to assume this is working, feel free to reopen if there are any problems.

**Comment by marshallward** [comment]
Minor update: I am considering turning this on by default, assuming it doesn't break anything.  (Tests are OK, but a few unexpected cases are giving garbage.)

**Comment by marshallward** [comment]
"Dense" arrays is now the default behavior.  To enable the old behaviour, use the `sparse_arrays` property (rather than `dense_arrays`).  In your case, no change is needed  :).
