### ISSUE TITLE
can't parse group names that contain a period

### ISSUE THREAD

**Issue by aekiss** [marshallward/f90nml#51]
I have a namelist from GFDL that contains this group:

 &diag_inESM2_Control_216.xmltegral_nml
       file_name  = 'diag_integral.out',
       time_units = 'days',
       output_interval = 1.0
/

for which f90nml.read gives the following error:

  File "/Users/andy/bin/nmltab.py", line 49, in nmldict
    nmlall[nml] = f90nml.read(nml, strict_logical=False)
  File "/Users/andy/Documents/COSIMA/github/aekiss/f90nml/f90nml/__init__.py", line 53, in read
    return parser.read(nml_path)
  File "/Users/andy/Documents/COSIMA/github/aekiss/f90nml/f90nml/parser.py", line 108, in read
    return self.readstream(nml_file, nml_patch)
  File "/Users/andy/Documents/COSIMA/github/aekiss/f90nml/f90nml/parser.py", line 125, in readstream
    toks = tokenizer.parse(line)
  File "/Users/andy/Documents/COSIMA/github/aekiss/f90nml/f90nml/tokenizer.py", line 71, in parse
    raise ValueError
ValueError

I've confirmed that the error goes away when the period is removed from &diag_inESM2_Control_216.xmltegral_nml

**Comment by marshallward** [comment]
Surprised that even works, AFAIK that is not a valid namelist name.  From the standard,

- *namelist-group-object* is a *variable-name* (5.6, line 9)
- *variable-name* is a *name* (6.2, line 20)
- *name* is *letter [alphannumeric-character] ...* (3.2.2, line 14)

But it wouldn't be the first time that non-standard stuff has worked.

Supporting this should probably be done with a strictness flag.

**Comment by marshallward** [comment]
I can't get gfortran or ifort to compile something with the dot, am I interpreting this right?

**Comment by aekiss** [comment]
Steve sent me the namelist containing that group - it's from a GFDL ESM2M config but that's about all I know. I was only interested in the MOM groups so the offending &diag_inESM2_Control_216.xmltegral_nml is not actually of interest to me. I don't know if they process it somehow before sending to their model - perhaps the diag_inESM2_Control_216. is stripped off by a preprocessor?
So anyway if this is not a valid name and gfortran & ifort don't handle it then it probably isn't worth fixing...? Though if GFDL use f90nml they might encounter this.

**Comment by marshallward** [comment]
There seems to be a "diag_integral_nml" entries in MOM.. but anyway this is not looking like a f90nml issue.

It might be worth supporting this, I think it's valuable to support preprocessed namelists, though as mentioned before it should be flag-controlled.

**Comment by marshallward** [comment]
Actually this is starting to look like a typo.. like the word `ESM2_Control_216.xml` got pasted in the `diag_integral_nml` name.  Suggest we close this?

**Comment by aekiss** [comment]
D'oh! Yes that's what it is. Sorry to have wasted your time - I'll let Steve know. Happy to close this.
