### ISSUE TITLE
Bump version on PyPi

### ISSUE THREAD

**Issue by jamesp** [marshallward/f90nml#52]
Bug fix that was merged in #44 is not in the PyPi code repo so
`pip install f90nml`
installs the old version.  Could you please update the version of the code hosted at pypi.

**Comment by marshallward** [comment]
Sorry, dealing with a bit of a github backlog at the moment.  I'd like to sort out #50 before doing a version update, but will try to get it up soon.

**Comment by jamesp** [comment]
No problem, thanks for the update.

**Comment by marshallward** [comment]
Sorry for the exceptionally long delay, I was putting off a pull request that is now sorted out.  PyPI has been updated to 0.22 which includes your changes.
