### ISSUE TITLE
String line continuation removal 

### ISSUE THREAD

**Issue by rgieseke** [marshallward/f90nml#54]
I'm using f90nml (many thanks for your library!) in https://github.com/openclimatedata/pymagicc

I think this commit in 0.22 broke reading of some nml files for me:
https://github.com/marshallward/f90nml/commit/b46fffef573f9c1cb0a3ccb0355b94508fed7178

The wrapped Fortran binary is producing multi-line strings. Not sure how common these are in Fortran. I don't think there are necessary in my case. 

Would it be worth having this as an option? I try to work around this in my files.

In any case might be good to put this in the changelog as well?

**Comment by marshallward** [comment]
That patch was related to the new tokenizer, so should not have changed the behaviour.  Multiline strings ought to work (assuming the compiler understands them), so I must have broken something.

Can you put up an example which is not working?

**Comment by marshallward** [comment]
Confirmed, this is just a flat-out bug.  I don't think that particular commit would have broken this problem, since it was looking for `(&, \n)` pairs as in Fortran source code.  But this definitely worked in 0.21, which did not use the new tokenizer, which is not respecting string line continuations.

I will try to fix this soon.

**Comment by marshallward** [comment]
I've pushed a change here that ought to work, can you try it for me?

**Comment by rgieseke** [comment]
Many thanks for the quick reply and fix! Some functions work again, but one file is still causing problems. I'll try to identify in detail tomorrow and will send you a proper test case.

**Comment by rgieseke** [comment]
Ok, I found the 'line' that causes problems:

```
&NML_ALLCFGS
PATHNAME_INFILES        = "

"
/
```

[TEST.txt](https://github.com/marshallward/f90nml/files/1502885/TEST.txt)

Error message:
```py
~/Work/pymagicc/venv/lib/python3.6/site-packages/f90nml/parser.py in readstream(self, nml_file, nml_patch)
    125             while tokenizer.prior_delim:
    126                 new_toks = tokenizer.parse(next(nml_file))
--> 127                 if new_toks[0].isspace():
    128                     toks[-1] += new_toks.pop(0)
    129                 toks[-1] += new_toks[0]

IndexError: list index out of range

```

So the empty extra line is the problem here, without it and your last commit it works fine.
The files that I'm reading have Windows line endings, not sure if that matters.

**Comment by marshallward** [comment]
Should the string be zero length in this case?   If so then a length check
seems to work fine.

**Comment by marshallward** [comment]
I've pushed another change, can you give it a try?

**Comment by rgieseke** [comment]
This works if the string is empty, but the original output file has trailing whitespace unfortunately.
(My editor seems to have removed it, attached again with trailing whitespace.)

[TEST_WS.txt](https://github.com/marshallward/f90nml/files/1502919/TEST_WS.txt)

**Comment by marshallward** [comment]
OK, new patch, try it now?

**Comment by rgieseke** [comment]
Everything working again, thank you so much!
