### ISSUE TITLE
1-based indexing is assumed but incompletely

### ISSUE THREAD

**Issue by sound-fx** [marshallward/f90nml#62]
I'm using f90nml ver. 0.23. Thank you for the nice package.

In the `var_strings` method of the `Namelist` class, please consider replacing the expression

`    i_s = v_start[::-1][len(v_idx)]`

with

`    i_s = v_start[::-1][len(v_idx)] if v_start is not None else 1`

The method has two instances of this expression, and one of them sometimes raises an exception when my code calls the `write` method on its `Namelist` object:

`TypeError: 'NoneType' object has no attribute '__getitem__'`

It's quite possible that my own code is entirely at fault for the exception. Only one of my ~1500 test cases triggers the exception, and I haven't yet figured out what's special about this one case.

**Comment by marshallward** [comment]
That change is less than an hour old, that is a fast test!

The change was in response to #61, could you post an example namelist or code snippet?  Thanks

**Comment by marshallward** [comment]
Actually wait.. that is the change that I just made about an hour ago.  Could you try the latest version?

**Comment by sound-fx** [comment]
I confirm that my tests run to successful completion with the latest version.

Note that the latest version retains one instance of the expression
`i_s = v_start[::-1][len(v_idx)]`
on line 418.  This will raise an exception if `v_start` has the default value `None`.

**Comment by marshallward** [comment]
Thanks for finding that, it's unfortunately found a bug that's not so easily fixed (specifically outlined in the FIXME comment.)  I'll open a separate ticket.
