### ISSUE TITLE
Question: adding a vector

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#68]
This is probably something simple...but I can't figure out how to do it.

Say I have the namelist:

```fortran
&vars
    v%vec(1) = 1,
    v%vec(2) = 2,
    v%vec(3) = 3,
    v%blah = 1,
/
```

And I want to add some variables to it (specifically a vector variable). Using this code:

```python
import f90nml

p = f90nml.Parser()
p.global_start_index = 1

data = p.read('test.nml')

data['vars']['v']['add_scalar'] = 'scalar'

data['vars']['v']['add_vec_2'] = ['first']

with open('test2.nml','w') as f:
    data.write(f, force=True)
```

produces this result:

```fortran
&vars
    v%vec(1:3) = 1, 2, 3
    v%blah = 1
    v%add_scalar = 'scalar'
    v%add_vec_2 = 'first'
/
```
What I want is for the last line to be `v%add_vec_2(1) = 'first'`, but it seems like the vector info is being stripped out. How can I get the array indices to print? Or why is it printing them for one variable and not the other? (FYI: I'm using v0.21).

**Comment by marshallward** [comment]
I think I understand the problem (after your edit).  It's handling everything OK internally but is defaulting to index-less array printing.

You can fix it in two ways:

    data['vars']['v'].start_index['add_vec_2'] = [1]

or (in 1.0.x):

    data.default_start_index = 1

Setting the start index is still a bit clunky, mostly because it was mainly intended as an internal variable, but tthere is room for improvement.

**Comment by marshallward** [comment]
Had a question I forgot to ask.  Are these indexes mandatory for derived types?  I know the rules around them can be more aggressive.

**Comment by jacobwilliams** [comment]
Thanks! I'll update and use `data.default_start_index = 1` version.

Yes, in my case, I want to always see the indices. I haven't seen any problems with derived types. If I do, I'll let you know.
