### ISSUE TITLE
Problem with missing index

### ISSUE THREAD

**Issue by LSchueler** [marshallward/f90nml#69]
I need to read in a namelist like this:

```
&test
var(1)%a = 1
var%b    = 2
/
```

Doing so in the accompanied Fortran program causes no problems, but reading it with f90nml gives me

```
File "f90nml/parser.py", line 487, in _parse_variable
    assert dt_idx is not None
AssertionError
```

I'm not sure if leaving out the index is against the namelist format or if this is a bug in your code. I had a look into the problematic code, but couldn't see a quick fix.

**Comment by marshallward** [comment]
Yep, I can reproduce this.  If this namelist is valid in any Fortran program, then I'd consider it to be a bug in f90nml.

Just for my own benefit, can you also include the valid Fortran code that goes with this?

**Comment by marshallward** [comment]
Nevermind, I manged to get something that works.
```
program y
    implicit none

    type z
        integer :: a
        integer :: b
    end type

    type(z), dimension(2) :: var
    namelist /test/ var

    open(10, file="x.nml")
    read(10, nml=test)
end program y
```

**Comment by marshallward** [comment]
This should be fixed in the newest commit (644d786), can you report back to see if it works?

**Comment by LSchueler** [comment]
It works like a charm! Thank you for your work and your very fast responses.

**Comment by marshallward** [comment]
Glad to hear, thanks for reporting it!
