### ISSUE TITLE
repeated variables are read as 1-element list

### ISSUE THREAD

**Issue by aekiss** [marshallward/f90nml#82]
Hi Marshall

Just posting that issue here so it isn't forgotten...

`f90nml.read()` will return `Namelist([('test', Namelist([('a', [3])]))])` (ie a is read as a list) when reading this 
```
&test
    a = 1
    a = 2
    a = 3
/
```
whereas Fortran will read the scalar a=3.

cheers
Andrew

**Comment by marshallward** [comment]
Definitely a bug.  My guess is that the repeated variables are triggering something to make it think that it's a list.  But I will look into it.
