### ISSUE TITLE
patch fails with empty dictionary

### ISSUE THREAD

**Issue by amicitas** [marshallward/f90nml#83]
It can be useful to call `patch` with an empty patch`nml` or `dict`. This is especially important for programmatic use.

**example**
The following command
```
patch = {}
f90nml.patch(file_in, patch, file_out)
```
produces no output file.

**Problem:**
`f90nml.parser.Parser.read` currently uses simple truth testing to see if a patch was provided. 

**solution (simple)**
`f90nml.parser.Parser.read` should explicitly check for `None`, or use `isinstance`.

**solution (better)**
add a new method `f90nml.parser.Parser.patch`.

[edit: sorry for all the edits]

**Comment by amicitas** [comment]
I'll make a pull request with a patch as soon as I have time to do so . . . (the patch is dead simple, I just need to find 30 minutes to make the pull request correctly).

**Comment by marshallward** [comment]
Confirmed, this change appears to fix things:
```
diff --git a/f90nml/parser.py b/f90nml/parser.py
index 4af684b..033ce81 100644
--- a/f90nml/parser.py
+++ b/f90nml/parser.py
@@ -237,7 +237,7 @@ class Parser(object):
         patch_is_path = not hasattr(patch_fname, 'read')
 
         # Convert patch data to a Namelist object
-        if nml_patch_in:
+        if nml_patch_in is not None:
             if not isinstance(nml_patch_in, dict):
                 raise TypeError('Input patch must be a dict or a Namelist.')
```
Happy to either make the change or let you do it, whichever you prefer.

Thanks for reporting this, `patch` is starting to get more use and issues with it are coming up more frequently.

**Comment by marshallward** [comment]
Also proposing this test:
```
+    def test_patch_null(self):
+        try:
+            f90nml.patch('types.nml', {}, 'tmp.nml')
+            self.assert_file_equal('types.nml', 'tmp.nml')
+        finally:
+            os.remove('tmp.nml')
```

**Comment by marshallward** [comment]
as for introducing a new `patch` function, are you suggesting to leave `Parser._readstream` unchanged, and just split some of the logic in `Parser.read`?

**Comment by amicitas** [comment]
Your patch to `Parser' works perfectly and resolves this issue. The test, attached to the top level api, looks good to me and seems robust against possible future internal implementation changes. 

Thank you for making this change (and even more so for developing this package in the first place).  I am going to move the idea of adding a patch method to Parser into a new issue for discussion.
