### ISSUE TITLE
deep copy of namelists

### ISSUE THREAD

**Issue by mhaselsteiner** [marshallward/f90nml#88]
It would be great if there was a method to create a deep copy of a Namelist in the same way you can do it with pandas DataFrames:
```python
initial_namelist = f90nml.Namelist()
second_namelist = initial_namelist.copy(deep=True)
```

**Comment by marshallward** [comment]
Just had a bit of play with `copy.deepcopy` and, to my somewhat surprise, it does seem to be copying the `start_index` property across namelists, so this may be more robust than I had originally thought.

**Comment by mhaselsteiner** [comment]
Thanks for getting back to me so quickly :) . I used it like this too, but was a bit unsure about it having any side effects. So thanks for testing. Plus, I think a method would be nice for convience. I understand the concern about redefining copy(), but it could also be just a new one e.g. deep_copy() . But this might just be a personal preference

**Comment by marshallward** [comment]
If there's some case which fails under `copy.deepcopy()`, then it definitely ought to be added.  But if `copy.deepcopy()` works, then I'm a bit reluctant to add the function.

I'd say let's sit on this and feel the issue out more before acting on it.

**Comment by jacobwilliams** [comment]
FYI: I've been using `copy.deepcopy` with the namelist structure for a long while and never had any problems. ¯\_(ツ)_/¯

**Comment by marshallward** [comment]
Going to close this, but please reopen if some issue with `deepcopy` comes up.
