### ISSUE TITLE
Handling of -inf

### ISSUE THREAD

**Issue by jenssss** [marshallward/f90nml#89]
Hi

I'm having trouble with the parsing of the following namelist
```
&group
  var=-inf
/
```
It's being parsed as `Namelist([('group', Namelist([('var', ['-', inf])]))])`, so I get the list `['-', inf]` instead of the float `-inf`.

Best
Jens

**Comment by marshallward** [comment]
Yep, bug is confirmed.  It may be necessary to make `-inf` a new token.  I will try to fix this tonight.

**Comment by jenssss** [comment]
It works with that change. Thanks!

**Comment by marshallward** [comment]
Great, it also should fix a few other cases, like `+Inf` and `±NaN`.

I'll close this issue, and see about doing a release soon.
