### ISSUE TITLE
Some bug in write

### ISSUE THREAD

**Issue by jacobwilliams** [marshallward/f90nml#9]
The following namelist triggers some sort of bug in the ```write``` routine:

````Fortran
 &blah
  a%vab_bbb%bbb = 1,
  a%vab_fffff%mmmmmmm%i = 399,
  a%c = 10000.0
 /
````

The code:
````Python
import f90nml
n = f90nml.read('test.txt')
n.write('test.nml')
````
produces the file:

````Fortran
&blah
    a%vab_bbb%bbb = 1
    a%vab_fffff%mmmmmmm%i =
    a%c = 10000.0
/
````
Interestingly, if you delete one of the m's in ````mmmmmmm```` , it works.

**Comment by marshallward** [comment]
Thanks, I can confirm the bug.

Odd that it prints the comma... usually it doesn't do that.

**Comment by marshallward** [comment]
Seems that it's a bug in the line-breaking code inside `namelist.py`. It is reporting that line as a length of -2. Sadly I did not review this part very carefully, I was just happy that it split the lines with some proficiency.

Very likely that I'm not accounting for the derived type entry length. I'll take a look at this tonight.

**Comment by marshallward** [comment]
master branch should be fixed now
can you give it a try?

**Comment by jacobwilliams** [comment]
This one is still not working:
````Fortran
 &test2
 aaaaaaaaaaaaaaa%hhhhhhhhhhhhhhhhhhhh = 1,
 aaaaaaaaaaaaaaa%iiiiiiiiiiiiiii = 2,
 aaaaaaaaaaaaaaa%jjjjjjjjjjjjjjjjjjjjjjj = 3,
 /
````

**Comment by marshallward** [comment]
Confirmed, it's a similar bug (or maybe just never fixed the original one)
I've put in a patch that should fix it.
Can you try it out?

**Comment by jacobwilliams** [comment]
Works great! Thanks!
