### ISSUE TITLE
Community guidlines

### ISSUE THREAD

**Issue by zbeekman** [marshallward/f90nml#95]
The [JOSS review] criteria state:
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

1. Please add a `CONTRIBUTING.md` or appropriate section to the README and/or utilize github issue and PR templates to document how to contribute to the software
2. In `CONTRIBUTING.md` or README, or in an issue template, please provide some minimal guidelines on reporting problems and issues
3. In `CONTRIBUTING.md` or the README describe how to seek support. It may be as simple as "file an issue or PR describing the problem".

[JOSS review]: https://github.com/openjournals/joss-reviews/issues/1474

**Comment by marshallward** [comment]
Thanks, will finish this off tonight.

**Comment by marshallward** [comment]
I've attached a contributing readme: 5a13db9eb6715217faee91ffdb3de593ff8d0c1d

First one I've written, but hopefully it hits all the key points.

**Comment by zbeekman** [comment]
Looks great! Only other request might be to link to it from README or read the docs.

**Comment by marshallward** [comment]
I've incorporated the contributing guidelines into the Sphinx docs, and added a link into the README.

**Comment by zbeekman** [comment]
LGTM!
