### ISSUE TITLE
Documentation for --output is wrong

### ISSUE THREAD

**Issue by zbeekman** [marshallward/f90nml#97]
The group selection documentation is repeated for the `--output` flag documentation when `--help` is passed.

```
$  f90nml --help
usage: f90nml [-h] [--version] [--group GROUP] [--variable VARIABLE] [--patch]
              [--format FORMAT] [--output OUTPUT]
              [input] [output]

...

  --group GROUP, -g GROUP
                        specify namelist group to modify. When absent, the
                        first group is used

...

  --output OUTPUT, -o OUTPUT
                        specify namelist group to modify. When absent, the
                        first group is used
```

Relates to https://github.com/openjournals/joss-reviews/issues/1474

**Comment by marshallward** [comment]
Thanks, I am not even sure why there is an output flag in this case.  This has been removed from the source and the docs, and now relies on the positional argument.  (2942d93fc0a1a8487b1c5dd8feb71e4b82dfdf11)

**Comment by zbeekman** [comment]
I was very confused for a brief moment. I thought that by

> This has been removed from the source and the docs, and now relies on the positional argument.

you were referring to an extant commit on master, not a new one you just pushed. 😅 

I'll test then close.

**Comment by marshallward** [comment]
Sorry!  Badly worded reply :)  Thanks for catching that error, btw.

**Comment by zbeekman** [comment]
np!
